# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/jackson/Programming/Git/gazette_Color-schemes

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/jackson/Programming/Git/gazette_Color-schemes

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running interactive CMake command-line interface..."
	/usr/bin/cmake -i .
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: install/local
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: install/strip
.PHONY : install/strip/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/jackson/Programming/Git/gazette_Color-schemes/CMakeFiles /home/jackson/Programming/Git/gazette_Color-schemes/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/jackson/Programming/Git/gazette_Color-schemes/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named gazette

# Build rule for target.
gazette: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 gazette
.PHONY : gazette

# fast build rule for target.
gazette/fast:
	$(MAKE) -f CMakeFiles/gazette.dir/build.make CMakeFiles/gazette.dir/build
.PHONY : gazette/fast

#=============================================================================
# Target rules for targets named i18n

# Build rule for target.
i18n: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 i18n
.PHONY : i18n

# fast build rule for target.
i18n/fast:
	$(MAKE) -f po/CMakeFiles/i18n.dir/build.make po/CMakeFiles/i18n.dir/build
.PHONY : i18n/fast

#=============================================================================
# Target rules for targets named pot

# Build rule for target.
pot: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 pot
.PHONY : pot

# fast build rule for target.
pot/fast:
	$(MAKE) -f po/CMakeFiles/pot.dir/build.make po/CMakeFiles/pot.dir/build
.PHONY : pot/fast

#=============================================================================
# Target rules for targets named Gazette

# Build rule for target.
Gazette: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Gazette
.PHONY : Gazette

# fast build rule for target.
Gazette/fast:
	$(MAKE) -f src/Plugs/CMakeFiles/Gazette.dir/build.make src/Plugs/CMakeFiles/Gazette.dir/build
.PHONY : Gazette/fast

src/Config.o: src/Config.c.o
.PHONY : src/Config.o

# target to build an object file
src/Config.c.o:
	$(MAKE) -f CMakeFiles/gazette.dir/build.make CMakeFiles/gazette.dir/src/Config.c.o
.PHONY : src/Config.c.o

src/Config.i: src/Config.c.i
.PHONY : src/Config.i

# target to preprocess a source file
src/Config.c.i:
	$(MAKE) -f CMakeFiles/gazette.dir/build.make CMakeFiles/gazette.dir/src/Config.c.i
.PHONY : src/Config.c.i

src/Config.s: src/Config.c.s
.PHONY : src/Config.s

# target to generate assembly for a file
src/Config.c.s:
	$(MAKE) -f CMakeFiles/gazette.dir/build.make CMakeFiles/gazette.dir/src/Config.c.s
.PHONY : src/Config.c.s

src/Gazette.o: src/Gazette.c.o
.PHONY : src/Gazette.o

# target to build an object file
src/Gazette.c.o:
	$(MAKE) -f CMakeFiles/gazette.dir/build.make CMakeFiles/gazette.dir/src/Gazette.c.o
.PHONY : src/Gazette.c.o

src/Gazette.i: src/Gazette.c.i
.PHONY : src/Gazette.i

# target to preprocess a source file
src/Gazette.c.i:
	$(MAKE) -f CMakeFiles/gazette.dir/build.make CMakeFiles/gazette.dir/src/Gazette.c.i
.PHONY : src/Gazette.c.i

src/Gazette.s: src/Gazette.c.s
.PHONY : src/Gazette.s

# target to generate assembly for a file
src/Gazette.c.s:
	$(MAKE) -f CMakeFiles/gazette.dir/build.make CMakeFiles/gazette.dir/src/Gazette.c.s
.PHONY : src/Gazette.c.s

src/Services/Calendar.o: src/Services/Calendar.c.o
.PHONY : src/Services/Calendar.o

# target to build an object file
src/Services/Calendar.c.o:
	$(MAKE) -f CMakeFiles/gazette.dir/build.make CMakeFiles/gazette.dir/src/Services/Calendar.c.o
.PHONY : src/Services/Calendar.c.o

src/Services/Calendar.i: src/Services/Calendar.c.i
.PHONY : src/Services/Calendar.i

# target to preprocess a source file
src/Services/Calendar.c.i:
	$(MAKE) -f CMakeFiles/gazette.dir/build.make CMakeFiles/gazette.dir/src/Services/Calendar.c.i
.PHONY : src/Services/Calendar.c.i

src/Services/Calendar.s: src/Services/Calendar.c.s
.PHONY : src/Services/Calendar.s

# target to generate assembly for a file
src/Services/Calendar.c.s:
	$(MAKE) -f CMakeFiles/gazette.dir/build.make CMakeFiles/gazette.dir/src/Services/Calendar.c.s
.PHONY : src/Services/Calendar.c.s

src/Services/Files.o: src/Services/Files.c.o
.PHONY : src/Services/Files.o

# target to build an object file
src/Services/Files.c.o:
	$(MAKE) -f CMakeFiles/gazette.dir/build.make CMakeFiles/gazette.dir/src/Services/Files.c.o
.PHONY : src/Services/Files.c.o

src/Services/Files.i: src/Services/Files.c.i
.PHONY : src/Services/Files.i

# target to preprocess a source file
src/Services/Files.c.i:
	$(MAKE) -f CMakeFiles/gazette.dir/build.make CMakeFiles/gazette.dir/src/Services/Files.c.i
.PHONY : src/Services/Files.c.i

src/Services/Files.s: src/Services/Files.c.s
.PHONY : src/Services/Files.s

# target to generate assembly for a file
src/Services/Files.c.s:
	$(MAKE) -f CMakeFiles/gazette.dir/build.make CMakeFiles/gazette.dir/src/Services/Files.c.s
.PHONY : src/Services/Files.c.s

src/Services/News.o: src/Services/News.c.o
.PHONY : src/Services/News.o

# target to build an object file
src/Services/News.c.o:
	$(MAKE) -f CMakeFiles/gazette.dir/build.make CMakeFiles/gazette.dir/src/Services/News.c.o
.PHONY : src/Services/News.c.o

src/Services/News.i: src/Services/News.c.i
.PHONY : src/Services/News.i

# target to preprocess a source file
src/Services/News.c.i:
	$(MAKE) -f CMakeFiles/gazette.dir/build.make CMakeFiles/gazette.dir/src/Services/News.c.i
.PHONY : src/Services/News.c.i

src/Services/News.s: src/Services/News.c.s
.PHONY : src/Services/News.s

# target to generate assembly for a file
src/Services/News.c.s:
	$(MAKE) -f CMakeFiles/gazette.dir/build.make CMakeFiles/gazette.dir/src/Services/News.c.s
.PHONY : src/Services/News.c.s

src/Services/Service.o: src/Services/Service.c.o
.PHONY : src/Services/Service.o

# target to build an object file
src/Services/Service.c.o:
	$(MAKE) -f CMakeFiles/gazette.dir/build.make CMakeFiles/gazette.dir/src/Services/Service.c.o
.PHONY : src/Services/Service.c.o

src/Services/Service.i: src/Services/Service.c.i
.PHONY : src/Services/Service.i

# target to preprocess a source file
src/Services/Service.c.i:
	$(MAKE) -f CMakeFiles/gazette.dir/build.make CMakeFiles/gazette.dir/src/Services/Service.c.i
.PHONY : src/Services/Service.c.i

src/Services/Service.s: src/Services/Service.c.s
.PHONY : src/Services/Service.s

# target to generate assembly for a file
src/Services/Service.c.s:
	$(MAKE) -f CMakeFiles/gazette.dir/build.make CMakeFiles/gazette.dir/src/Services/Service.c.s
.PHONY : src/Services/Service.c.s

src/Services/Weather.o: src/Services/Weather.c.o
.PHONY : src/Services/Weather.o

# target to build an object file
src/Services/Weather.c.o:
	$(MAKE) -f CMakeFiles/gazette.dir/build.make CMakeFiles/gazette.dir/src/Services/Weather.c.o
.PHONY : src/Services/Weather.c.o

src/Services/Weather.i: src/Services/Weather.c.i
.PHONY : src/Services/Weather.i

# target to preprocess a source file
src/Services/Weather.c.i:
	$(MAKE) -f CMakeFiles/gazette.dir/build.make CMakeFiles/gazette.dir/src/Services/Weather.c.i
.PHONY : src/Services/Weather.c.i

src/Services/Weather.s: src/Services/Weather.c.s
.PHONY : src/Services/Weather.s

# target to generate assembly for a file
src/Services/Weather.c.s:
	$(MAKE) -f CMakeFiles/gazette.dir/build.make CMakeFiles/gazette.dir/src/Services/Weather.c.s
.PHONY : src/Services/Weather.c.s

src/Widgets/GazetteWindow.o: src/Widgets/GazetteWindow.c.o
.PHONY : src/Widgets/GazetteWindow.o

# target to build an object file
src/Widgets/GazetteWindow.c.o:
	$(MAKE) -f CMakeFiles/gazette.dir/build.make CMakeFiles/gazette.dir/src/Widgets/GazetteWindow.c.o
.PHONY : src/Widgets/GazetteWindow.c.o

src/Widgets/GazetteWindow.i: src/Widgets/GazetteWindow.c.i
.PHONY : src/Widgets/GazetteWindow.i

# target to preprocess a source file
src/Widgets/GazetteWindow.c.i:
	$(MAKE) -f CMakeFiles/gazette.dir/build.make CMakeFiles/gazette.dir/src/Widgets/GazetteWindow.c.i
.PHONY : src/Widgets/GazetteWindow.c.i

src/Widgets/GazetteWindow.s: src/Widgets/GazetteWindow.c.s
.PHONY : src/Widgets/GazetteWindow.s

# target to generate assembly for a file
src/Widgets/GazetteWindow.c.s:
	$(MAKE) -f CMakeFiles/gazette.dir/build.make CMakeFiles/gazette.dir/src/Widgets/GazetteWindow.c.s
.PHONY : src/Widgets/GazetteWindow.c.s

src/Widgets/ShadowedLabel.o: src/Widgets/ShadowedLabel.c.o
.PHONY : src/Widgets/ShadowedLabel.o

# target to build an object file
src/Widgets/ShadowedLabel.c.o:
	$(MAKE) -f CMakeFiles/gazette.dir/build.make CMakeFiles/gazette.dir/src/Widgets/ShadowedLabel.c.o
.PHONY : src/Widgets/ShadowedLabel.c.o

src/Widgets/ShadowedLabel.i: src/Widgets/ShadowedLabel.c.i
.PHONY : src/Widgets/ShadowedLabel.i

# target to preprocess a source file
src/Widgets/ShadowedLabel.c.i:
	$(MAKE) -f CMakeFiles/gazette.dir/build.make CMakeFiles/gazette.dir/src/Widgets/ShadowedLabel.c.i
.PHONY : src/Widgets/ShadowedLabel.c.i

src/Widgets/ShadowedLabel.s: src/Widgets/ShadowedLabel.c.s
.PHONY : src/Widgets/ShadowedLabel.s

# target to generate assembly for a file
src/Widgets/ShadowedLabel.c.s:
	$(MAKE) -f CMakeFiles/gazette.dir/build.make CMakeFiles/gazette.dir/src/Widgets/ShadowedLabel.c.s
.PHONY : src/Widgets/ShadowedLabel.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... gazette"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... i18n"
	@echo "... pot"
	@echo "... Gazette"
	@echo "... src/Config.o"
	@echo "... src/Config.i"
	@echo "... src/Config.s"
	@echo "... src/Gazette.o"
	@echo "... src/Gazette.i"
	@echo "... src/Gazette.s"
	@echo "... src/Services/Calendar.o"
	@echo "... src/Services/Calendar.i"
	@echo "... src/Services/Calendar.s"
	@echo "... src/Services/Files.o"
	@echo "... src/Services/Files.i"
	@echo "... src/Services/Files.s"
	@echo "... src/Services/News.o"
	@echo "... src/Services/News.i"
	@echo "... src/Services/News.s"
	@echo "... src/Services/Service.o"
	@echo "... src/Services/Service.i"
	@echo "... src/Services/Service.s"
	@echo "... src/Services/Weather.o"
	@echo "... src/Services/Weather.i"
	@echo "... src/Services/Weather.s"
	@echo "... src/Widgets/GazetteWindow.o"
	@echo "... src/Widgets/GazetteWindow.i"
	@echo "... src/Widgets/GazetteWindow.s"
	@echo "... src/Widgets/ShadowedLabel.o"
	@echo "... src/Widgets/ShadowedLabel.i"
	@echo "... src/Widgets/ShadowedLabel.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

