/* Calendar.c generated by valac 0.20.1, the Vala compiler
 * generated from Calendar.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <clutter/clutter.h>
#include <stdlib.h>
#include <string.h>
#include <float.h>
#include <math.h>


#define TYPE_SERVICE (service_get_type ())
#define SERVICE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_SERVICE, Service))
#define SERVICE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_SERVICE, ServiceClass))
#define IS_SERVICE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_SERVICE))
#define IS_SERVICE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_SERVICE))
#define SERVICE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_SERVICE, ServiceClass))

typedef struct _Service Service;
typedef struct _ServiceClass ServiceClass;
typedef struct _ServicePrivate ServicePrivate;

#define TYPE_CALENDAR (calendar_get_type ())
#define CALENDAR(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_CALENDAR, Calendar))
#define CALENDAR_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_CALENDAR, CalendarClass))
#define IS_CALENDAR(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_CALENDAR))
#define IS_CALENDAR_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_CALENDAR))
#define CALENDAR_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_CALENDAR, CalendarClass))

typedef struct _Calendar Calendar;
typedef struct _CalendarClass CalendarClass;
typedef struct _CalendarPrivate CalendarPrivate;

#define TYPE_SHADOWED_LABEL (shadowed_label_get_type ())
#define SHADOWED_LABEL(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_SHADOWED_LABEL, ShadowedLabel))
#define SHADOWED_LABEL_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_SHADOWED_LABEL, ShadowedLabelClass))
#define IS_SHADOWED_LABEL(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_SHADOWED_LABEL))
#define IS_SHADOWED_LABEL_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_SHADOWED_LABEL))
#define SHADOWED_LABEL_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_SHADOWED_LABEL, ShadowedLabelClass))

typedef struct _ShadowedLabel ShadowedLabel;
typedef struct _ShadowedLabelClass ShadowedLabelClass;
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))

struct _Service {
	ClutterActor parent_instance;
	ServicePrivate * priv;
};

struct _ServiceClass {
	ClutterActorClass parent_class;
	void (*create) (Service* self);
	gboolean (*update) (Service* self);
};

struct _Calendar {
	Service parent_instance;
	CalendarPrivate * priv;
};

struct _CalendarClass {
	ServiceClass parent_class;
};


static gpointer calendar_parent_class = NULL;

GType service_get_type (void) G_GNUC_CONST;
GType calendar_get_type (void) G_GNUC_CONST;
enum  {
	CALENDAR_DUMMY_PROPERTY
};
Calendar* calendar_new (void);
Calendar* calendar_construct (GType object_type);
Service* service_construct (GType object_type, const gchar* _id);
gboolean service_load (Service* self);
static void calendar_real_create (Service* base);
#define textcolor "black"
ShadowedLabel* shadowed_label_new (const gchar* _label);
ShadowedLabel* shadowed_label_construct (GType object_type, const gchar* _label);
GType shadowed_label_get_type (void) G_GNUC_CONST;
static gboolean calendar_real_update (Service* base);


Calendar* calendar_construct (GType object_type) {
	Calendar * self = NULL;
	self = (Calendar*) service_construct (object_type, "calendar");
	service_load ((Service*) self);
	return self;
}


Calendar* calendar_new (void) {
	return calendar_construct (TYPE_CALENDAR);
}


static void calendar_real_create (Service* base) {
	Calendar * self;
	ShadowedLabel* _tmp0_;
	ShadowedLabel* label;
	ShadowedLabel* _tmp1_;
	ShadowedLabel* content;
	gfloat _tmp2_;
	gfloat _tmp3_;
	self = (Calendar*) base;
	_tmp0_ = shadowed_label_new ("<span color='" textcolor "' face='Raleway' font='20'>Calendar</span>");
	g_object_ref_sink (_tmp0_);
	label = _tmp0_;
	_tmp1_ = shadowed_label_new ("<span color='" textcolor "' face='Raleway' font='19'> " "	January	" " </span>\n" "<span color='" textcolor "' face='Freemono' font='13'>S  M  T  W  T  F  S </span>\n" "<span color='" textcolor "' face='Freemono' font='13'>" "   1  2  3  4  5  6\n7  8  9 ..." "</span>");
	g_object_ref_sink (_tmp1_);
	content = _tmp1_;
	clutter_actor_set_x ((ClutterActor*) label, (gfloat) 0);
	clutter_actor_set_y ((ClutterActor*) label, (gfloat) 0);
	clutter_actor_set_x ((ClutterActor*) content, (gfloat) 2);
	_tmp2_ = clutter_actor_get_height ((ClutterActor*) label);
	_tmp3_ = _tmp2_;
	clutter_actor_set_y ((ClutterActor*) content, _tmp3_ + 12);
	clutter_actor_add_child ((ClutterActor*) self, (ClutterActor*) label);
	clutter_actor_add_child ((ClutterActor*) self, (ClutterActor*) content);
	_g_object_unref0 (content);
	_g_object_unref0 (label);
}


static gboolean calendar_real_update (Service* base) {
	Calendar * self;
	gboolean result = FALSE;
	self = (Calendar*) base;
	result = TRUE;
	return result;
}


static void calendar_class_init (CalendarClass * klass) {
	calendar_parent_class = g_type_class_peek_parent (klass);
	SERVICE_CLASS (klass)->create = calendar_real_create;
	SERVICE_CLASS (klass)->update = calendar_real_update;
}


static void calendar_instance_init (Calendar * self) {
}


GType calendar_get_type (void) {
	static volatile gsize calendar_type_id__volatile = 0;
	if (g_once_init_enter (&calendar_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (CalendarClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) calendar_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (Calendar), 0, (GInstanceInitFunc) calendar_instance_init, NULL };
		GType calendar_type_id;
		calendar_type_id = g_type_register_static (TYPE_SERVICE, "Calendar", &g_define_type_info, 0);
		g_once_init_leave (&calendar_type_id__volatile, calendar_type_id);
	}
	return calendar_type_id__volatile;
}



