/* Weather.c generated by valac 0.20.1, the Vala compiler
 * generated from Weather.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <stdlib.h>
#include <string.h>
#include <clutter/clutter.h>
#include <libsoup/soup.h>
#include <gio/gio.h>
#include <glib/gi18n-lib.h>


#define TYPE_SERVICE (service_get_type ())
#define SERVICE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_SERVICE, Service))
#define SERVICE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_SERVICE, ServiceClass))
#define IS_SERVICE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_SERVICE))
#define IS_SERVICE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_SERVICE))
#define SERVICE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_SERVICE, ServiceClass))

typedef struct _Service Service;
typedef struct _ServiceClass ServiceClass;
typedef struct _ServicePrivate ServicePrivate;

#define TYPE_WEATHER (weather_get_type ())
#define WEATHER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_WEATHER, Weather))
#define WEATHER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_WEATHER, WeatherClass))
#define IS_WEATHER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_WEATHER))
#define IS_WEATHER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_WEATHER))
#define WEATHER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_WEATHER, WeatherClass))

typedef struct _Weather Weather;
typedef struct _WeatherClass WeatherClass;
typedef struct _WeatherPrivate WeatherPrivate;

#define TYPE_SHADOWED_LABEL (shadowed_label_get_type ())
#define SHADOWED_LABEL(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_SHADOWED_LABEL, ShadowedLabel))
#define SHADOWED_LABEL_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_SHADOWED_LABEL, ShadowedLabelClass))
#define IS_SHADOWED_LABEL(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_SHADOWED_LABEL))
#define IS_SHADOWED_LABEL_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_SHADOWED_LABEL))
#define SHADOWED_LABEL_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_SHADOWED_LABEL, ShadowedLabelClass))

typedef struct _ShadowedLabel ShadowedLabel;
typedef struct _ShadowedLabelClass ShadowedLabelClass;
#define _g_free0(var) (var = (g_free (var), NULL))
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
#define _g_date_time_unref0(var) ((var == NULL) ? NULL : (var = (g_date_time_unref (var), NULL)))

struct _Service {
	ClutterActor parent_instance;
	ServicePrivate * priv;
};

struct _ServiceClass {
	ClutterActorClass parent_class;
	void (*create) (Service* self);
	gboolean (*update) (Service* self);
};

struct _Weather {
	Service parent_instance;
	WeatherPrivate * priv;
};

struct _WeatherClass {
	ServiceClass parent_class;
};

struct _WeatherPrivate {
	gchar** condition_texts;
	gint condition_texts_length1;
	gint _condition_texts_size_;
	gchar** day_texts;
	gint day_texts_length1;
	gint _day_texts_size_;
	gchar* unit;
	gchar* text;
	SoupSessionAsync* session;
	SoupMessage* message;
	GSettings* settings;
	ShadowedLabel* label;
	ShadowedLabel* reload;
};


static gpointer weather_parent_class = NULL;

GType service_get_type (void) G_GNUC_CONST;
GType weather_get_type (void) G_GNUC_CONST;
GType shadowed_label_get_type (void) G_GNUC_CONST;
#define WEATHER_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), TYPE_WEATHER, WeatherPrivate))
enum  {
	WEATHER_DUMMY_PROPERTY
};
Weather* weather_new (void);
Weather* weather_construct (GType object_type);
Service* service_construct (GType object_type, const gchar* _id);
static void __lambda12_ (Weather* self, const gchar* key);
gboolean service_update (Service* self);
static void ___lambda12__g_settings_changed (GSettings* _sender, const gchar* key, gpointer self);
ShadowedLabel* shadowed_label_new (const gchar* _label);
ShadowedLabel* shadowed_label_construct (GType object_type, const gchar* _label);
ShadowedLabel* service_get_reload_label (Service* self, const gchar* service_name);
gboolean service_load (Service* self);
static gboolean _service_update_gsource_func (gpointer self);
static void weather_real_create (Service* base);
gchar** weather_get_attributes (Weather* self, const gchar* data, const gchar* tagname, gchar** attrs, int attrs_length1, gint offset, int* result_length1);
gchar* weather_get_attribute_value (Weather* self, const gchar* data, const gchar* attr);
static gboolean weather_real_update (Service* base);
#define textcolor "blue"
void shadowed_label_set_label (ShadowedLabel* self, const gchar* value);
static void __lambda13_ (Weather* self, SoupSession* session, SoupMessage* m);
static void ___lambda13__soup_session_callback (SoupSession* session, SoupMessage* msg, gpointer self);
static void weather_finalize (GObject* obj);
static void _vala_array_destroy (gpointer array, gint array_length, GDestroyNotify destroy_func);
static void _vala_array_free (gpointer array, gint array_length, GDestroyNotify destroy_func);

const gchar* condition_codes[49] = {"c", "0", "c", "1", "1", "2", "3", "2", "e", "3", "7", "3", "3", "6", "G", "#", "h", "7", "7", "f", "f", "f", "M", "c", "S", "h", "N", "4", "3", "K", "J", "C", "B", "2", "B", "X", "1", "1", "1", "1", "e", "#", "2", "#", "H", "1", "2", "1", ")"};

static void __lambda12_ (Weather* self, const gchar* key) {
	g_return_if_fail (key != NULL);
	service_update ((Service*) self);
}


static void ___lambda12__g_settings_changed (GSettings* _sender, const gchar* key, gpointer self) {
	__lambda12_ (self, key);
}


static gboolean _service_update_gsource_func (gpointer self) {
	gboolean result;
	result = service_update (self);
	return result;
}


Weather* weather_construct (GType object_type) {
	Weather * self = NULL;
	GSettings* _tmp0_;
	GSettings* _tmp1_;
	ShadowedLabel* _tmp2_;
	const gchar* _tmp3_ = NULL;
	ShadowedLabel* _tmp4_ = NULL;
	ShadowedLabel* _tmp5_;
	SoupSessionAsync* _tmp6_;
	ShadowedLabel* _tmp7_;
	ShadowedLabel* _tmp8_;
	GSettings* _tmp9_;
	gint _tmp10_ = 0;
	self = (Weather*) service_construct (object_type, "weather");
	_tmp0_ = g_settings_new ("org.pantheon.gazette.weather");
	_g_object_unref0 (self->priv->settings);
	self->priv->settings = _tmp0_;
	_tmp1_ = self->priv->settings;
	g_signal_connect_object (_tmp1_, "changed", (GCallback) ___lambda12__g_settings_changed, self, 0);
	_tmp2_ = shadowed_label_new ("");
	g_object_ref_sink (_tmp2_);
	_g_object_unref0 (self->priv->label);
	self->priv->label = _tmp2_;
	_tmp3_ = _ ("weather");
	_tmp4_ = service_get_reload_label ((Service*) self, _tmp3_);
	_g_object_unref0 (self->priv->reload);
	self->priv->reload = _tmp4_;
	_tmp5_ = self->priv->reload;
	clutter_actor_hide ((ClutterActor*) _tmp5_);
	_tmp6_ = (SoupSessionAsync*) soup_session_async_new ();
	_g_object_unref0 (self->priv->session);
	self->priv->session = _tmp6_;
	_tmp7_ = self->priv->label;
	clutter_actor_add_child ((ClutterActor*) self, (ClutterActor*) _tmp7_);
	_tmp8_ = self->priv->reload;
	clutter_actor_add_child ((ClutterActor*) self, (ClutterActor*) _tmp8_);
	service_load ((Service*) self);
	_tmp9_ = self->priv->settings;
	_tmp10_ = g_settings_get_int (_tmp9_, "update-interval");
	g_timeout_add_full (G_PRIORITY_DEFAULT, (guint) _tmp10_, _service_update_gsource_func, g_object_ref ((Service*) self), g_object_unref);
	return self;
}


Weather* weather_new (void) {
	return weather_construct (TYPE_WEATHER);
}


static void weather_real_create (Service* base) {
	Weather * self;
	self = (Weather*) base;
}


static gint string_index_of (const gchar* self, const gchar* needle, gint start_index) {
	gint result = 0;
	gint _tmp0_;
	const gchar* _tmp1_;
	gchar* _tmp2_ = NULL;
	gchar* _result_;
	gchar* _tmp3_;
	g_return_val_if_fail (self != NULL, 0);
	g_return_val_if_fail (needle != NULL, 0);
	_tmp0_ = start_index;
	_tmp1_ = needle;
	_tmp2_ = strstr (((gchar*) self) + _tmp0_, (gchar*) _tmp1_);
	_result_ = _tmp2_;
	_tmp3_ = _result_;
	if (_tmp3_ != NULL) {
		gchar* _tmp4_;
		_tmp4_ = _result_;
		result = (gint) (_tmp4_ - ((gchar*) self));
		return result;
	} else {
		result = -1;
		return result;
	}
}


static glong string_strnlen (gchar* str, glong maxlen) {
	glong result = 0L;
	gchar* _tmp0_;
	glong _tmp1_;
	gchar* _tmp2_ = NULL;
	gchar* end;
	gchar* _tmp3_;
	_tmp0_ = str;
	_tmp1_ = maxlen;
	_tmp2_ = memchr (_tmp0_, 0, (gsize) _tmp1_);
	end = _tmp2_;
	_tmp3_ = end;
	if (_tmp3_ == NULL) {
		glong _tmp4_;
		_tmp4_ = maxlen;
		result = _tmp4_;
		return result;
	} else {
		gchar* _tmp5_;
		gchar* _tmp6_;
		_tmp5_ = end;
		_tmp6_ = str;
		result = (glong) (_tmp5_ - _tmp6_);
		return result;
	}
}


static gchar* string_substring (const gchar* self, glong offset, glong len) {
	gchar* result = NULL;
	glong string_length = 0L;
	gboolean _tmp0_ = FALSE;
	glong _tmp1_;
	gboolean _tmp3_;
	glong _tmp9_;
	glong _tmp15_;
	glong _tmp18_;
	glong _tmp19_;
	glong _tmp20_;
	glong _tmp21_;
	glong _tmp22_;
	gchar* _tmp23_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp1_ = offset;
	if (_tmp1_ >= ((glong) 0)) {
		glong _tmp2_;
		_tmp2_ = len;
		_tmp0_ = _tmp2_ >= ((glong) 0);
	} else {
		_tmp0_ = FALSE;
	}
	_tmp3_ = _tmp0_;
	if (_tmp3_) {
		glong _tmp4_;
		glong _tmp5_;
		glong _tmp6_ = 0L;
		_tmp4_ = offset;
		_tmp5_ = len;
		_tmp6_ = string_strnlen ((gchar*) self, _tmp4_ + _tmp5_);
		string_length = _tmp6_;
	} else {
		gint _tmp7_;
		gint _tmp8_;
		_tmp7_ = strlen (self);
		_tmp8_ = _tmp7_;
		string_length = (glong) _tmp8_;
	}
	_tmp9_ = offset;
	if (_tmp9_ < ((glong) 0)) {
		glong _tmp10_;
		glong _tmp11_;
		glong _tmp12_;
		_tmp10_ = string_length;
		_tmp11_ = offset;
		offset = _tmp10_ + _tmp11_;
		_tmp12_ = offset;
		g_return_val_if_fail (_tmp12_ >= ((glong) 0), NULL);
	} else {
		glong _tmp13_;
		glong _tmp14_;
		_tmp13_ = offset;
		_tmp14_ = string_length;
		g_return_val_if_fail (_tmp13_ <= _tmp14_, NULL);
	}
	_tmp15_ = len;
	if (_tmp15_ < ((glong) 0)) {
		glong _tmp16_;
		glong _tmp17_;
		_tmp16_ = string_length;
		_tmp17_ = offset;
		len = _tmp16_ - _tmp17_;
	}
	_tmp18_ = offset;
	_tmp19_ = len;
	_tmp20_ = string_length;
	g_return_val_if_fail ((_tmp18_ + _tmp19_) <= _tmp20_, NULL);
	_tmp21_ = offset;
	_tmp22_ = len;
	_tmp23_ = g_strndup (((gchar*) self) + _tmp21_, (gsize) _tmp22_);
	result = _tmp23_;
	return result;
}


gchar** weather_get_attributes (Weather* self, const gchar* data, const gchar* tagname, gchar** attrs, int attrs_length1, gint offset, int* result_length1) {
	gchar** result = NULL;
	const gchar* _tmp0_;
	const gchar* _tmp1_;
	gchar* _tmp2_;
	gchar* _tmp3_;
	gint _tmp4_;
	gint _tmp5_ = 0;
	const gchar* _tmp6_;
	gint _tmp7_;
	gint _tmp8_;
	gint _tmp9_;
	gint start;
	const gchar* _tmp10_;
	gint _tmp11_;
	gint _tmp12_ = 0;
	gint end;
	const gchar* _tmp13_;
	gint _tmp14_;
	gint _tmp15_;
	gint _tmp16_;
	gchar* _tmp17_ = NULL;
	gchar* tmp_data;
	gchar** _tmp18_;
	gint _tmp18__length1;
	gchar** _tmp19_ = NULL;
	gchar** res;
	gint res_length1;
	gint _res_size_;
	gchar** _tmp33_;
	gint _tmp33__length1;
	g_return_val_if_fail (self != NULL, NULL);
	g_return_val_if_fail (data != NULL, NULL);
	g_return_val_if_fail (tagname != NULL, NULL);
	_tmp0_ = data;
	_tmp1_ = tagname;
	_tmp2_ = g_strconcat ("<", _tmp1_, NULL);
	_tmp3_ = _tmp2_;
	_tmp4_ = offset;
	_tmp5_ = string_index_of (_tmp0_, _tmp3_, _tmp4_);
	_tmp6_ = tagname;
	_tmp7_ = strlen (_tmp6_);
	_tmp8_ = _tmp7_;
	_tmp9_ = (_tmp5_ + _tmp8_) + 1;
	_g_free0 (_tmp3_);
	start = _tmp9_;
	_tmp10_ = data;
	_tmp11_ = start;
	_tmp12_ = string_index_of (_tmp10_, "/>", _tmp11_);
	end = _tmp12_;
	_tmp13_ = data;
	_tmp14_ = start;
	_tmp15_ = end;
	_tmp16_ = start;
	_tmp17_ = string_substring (_tmp13_, (glong) _tmp14_, (glong) (_tmp15_ - _tmp16_));
	tmp_data = _tmp17_;
	_tmp18_ = attrs;
	_tmp18__length1 = attrs_length1;
	_tmp19_ = g_new0 (gchar*, _tmp18__length1 + 1);
	res = _tmp19_;
	res_length1 = _tmp18__length1;
	_res_size_ = res_length1;
	{
		gint i;
		i = 0;
		{
			gboolean _tmp20_;
			_tmp20_ = TRUE;
			while (TRUE) {
				gboolean _tmp21_;
				gint _tmp23_;
				gchar** _tmp24_;
				gint _tmp24__length1;
				gchar** _tmp25_;
				gint _tmp25__length1;
				gint _tmp26_;
				const gchar* _tmp27_;
				gchar** _tmp28_;
				gint _tmp28__length1;
				gint _tmp29_;
				const gchar* _tmp30_;
				gchar* _tmp31_ = NULL;
				gchar* _tmp32_;
				_tmp21_ = _tmp20_;
				if (!_tmp21_) {
					gint _tmp22_;
					_tmp22_ = i;
					i = _tmp22_ + 1;
				}
				_tmp20_ = FALSE;
				_tmp23_ = i;
				_tmp24_ = attrs;
				_tmp24__length1 = attrs_length1;
				if (!(_tmp23_ < _tmp24__length1)) {
					break;
				}
				_tmp25_ = res;
				_tmp25__length1 = res_length1;
				_tmp26_ = i;
				_tmp27_ = tmp_data;
				_tmp28_ = attrs;
				_tmp28__length1 = attrs_length1;
				_tmp29_ = i;
				_tmp30_ = _tmp28_[_tmp29_];
				_tmp31_ = weather_get_attribute_value (self, _tmp27_, _tmp30_);
				_g_free0 (_tmp25_[_tmp26_]);
				_tmp25_[_tmp26_] = _tmp31_;
				_tmp32_ = _tmp25_[_tmp26_];
			}
		}
	}
	_tmp33_ = res;
	_tmp33__length1 = res_length1;
	if (result_length1) {
		*result_length1 = _tmp33__length1;
	}
	result = _tmp33_;
	_g_free0 (tmp_data);
	return result;
}


gchar* weather_get_attribute_value (Weather* self, const gchar* data, const gchar* attr) {
	gchar* result = NULL;
	const gchar* _tmp0_;
	const gchar* _tmp1_;
	gchar* _tmp2_;
	gchar* _tmp3_;
	gint _tmp4_ = 0;
	const gchar* _tmp5_;
	gint _tmp6_;
	gint _tmp7_;
	gint _tmp8_;
	gint start;
	const gchar* _tmp9_;
	gint _tmp10_ = 0;
	gint end;
	const gchar* _tmp11_;
	gchar* _tmp12_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	g_return_val_if_fail (data != NULL, NULL);
	g_return_val_if_fail (attr != NULL, NULL);
	_tmp0_ = data;
	_tmp1_ = attr;
	_tmp2_ = g_strconcat (_tmp1_, "=\"", NULL);
	_tmp3_ = _tmp2_;
	_tmp4_ = string_index_of (_tmp0_, _tmp3_, 0);
	_tmp5_ = attr;
	_tmp6_ = strlen (_tmp5_);
	_tmp7_ = _tmp6_;
	_tmp8_ = (_tmp4_ + _tmp7_) + 2;
	_g_free0 (_tmp3_);
	start = _tmp8_;
	_tmp9_ = data;
	_tmp10_ = string_index_of (_tmp9_, "\"", start);
	end = _tmp10_;
	_tmp11_ = data;
	_tmp12_ = string_substring (_tmp11_, (glong) start, (glong) (end - start));
	result = _tmp12_;
	return result;
}


static gpointer _g_object_ref0 (gpointer self) {
	return self ? g_object_ref (self) : NULL;
}


static void __lambda13_ (Weather* self, SoupSession* session, SoupMessage* m) {
	SoupMessage* _tmp0_;
	SoupMessageBody* _tmp1_;
	guint8* _tmp2_;
	gint _tmp2__length1;
	gchar* _tmp3_;
	gchar* data;
	const gchar* _tmp4_;
	const gchar* _tmp7_;
	gchar* _tmp8_;
	gchar* _tmp9_;
	gchar* _tmp10_;
	gchar** _tmp11_ = NULL;
	gchar** _tmp12_;
	gint _tmp12__length1;
	gint _tmp13_ = 0;
	gchar** _tmp14_ = NULL;
	gchar** _tmp15_;
	gint _tmp15__length1;
	gchar** current;
	gint current_length1;
	gint _current_size_;
	const gchar* _tmp16_;
	gchar* _tmp17_;
	gchar* _tmp18_;
	gchar* _tmp19_;
	gchar* _tmp20_;
	gchar* _tmp21_;
	gchar* _tmp22_;
	gchar** _tmp23_ = NULL;
	gchar** _tmp24_;
	gint _tmp24__length1;
	const gchar* _tmp25_;
	gint _tmp26_ = 0;
	gint _tmp27_ = 0;
	gchar** _tmp28_ = NULL;
	gchar** _tmp29_;
	gint _tmp29__length1;
	gchar** forecast;
	gint forecast_length1;
	gint _forecast_size_;
	const gchar* _tmp30_;
	gchar* _tmp31_;
	gchar* _tmp32_;
	gchar* _tmp33_;
	gchar* _tmp34_;
	gchar* _tmp35_;
	gchar* _tmp36_;
	gchar** _tmp37_ = NULL;
	gchar** _tmp38_;
	gint _tmp38__length1;
	const gchar* _tmp39_;
	gint _tmp40_ = 0;
	gint _tmp41_ = 0;
	gchar** _tmp42_ = NULL;
	gchar** _tmp43_;
	gint _tmp43__length1;
	gchar** forecast2;
	gint forecast2_length1;
	gint _forecast2_size_;
	GDateTime* _tmp44_;
	GDateTime* _tmp45_;
	const gchar* _tmp46_ = NULL;
	gchar* _tmp47_ = NULL;
	gchar* _tmp48_;
	gchar* today;
	const gchar* _tmp49_ = NULL;
	gchar* _tmp50_ = NULL;
	gchar* _tmp51_;
	gchar* _tmp52_;
	gchar* _tmp53_;
	const gchar* _tmp54_;
	gchar* _tmp55_;
	gchar* _tmp56_;
	gchar* _tmp57_;
	gchar* _tmp58_;
	const gchar* _tmp59_ = NULL;
	gchar* _tmp60_ = NULL;
	gchar* _tmp61_;
	gchar* _tmp62_;
	gchar* _tmp63_;
	gchar* _tmp64_;
	gchar* _tmp65_;
	gchar** _tmp66_;
	gint _tmp66__length1;
	gchar** _tmp67_;
	gint _tmp67__length1;
	const gchar* _tmp68_;
	gint _tmp69_ = 0;
	const gchar* _tmp70_;
	gchar* _tmp71_;
	gchar* _tmp72_;
	gchar* _tmp73_;
	gchar* _tmp74_;
	const gchar* _tmp75_ = NULL;
	gchar* _tmp76_ = NULL;
	gchar* _tmp77_;
	gchar* _tmp78_;
	gchar* _tmp79_;
	gchar* _tmp80_;
	gchar* _tmp81_;
	gchar** _tmp82_;
	gint _tmp82__length1;
	const gchar* _tmp83_;
	gint _tmp84_ = 0;
	const gchar* _tmp85_;
	gchar* _tmp86_;
	gchar* _tmp87_;
	gchar* _tmp88_;
	gchar* _tmp89_;
	const gchar* _tmp90_ = NULL;
	gchar* _tmp91_ = NULL;
	gchar* _tmp92_;
	gchar* _tmp93_;
	gchar* _tmp94_;
	gchar* _tmp95_;
	gchar* _tmp96_;
	gchar** _tmp97_;
	gint _tmp97__length1;
	const gchar* _tmp98_;
	gchar* _tmp99_;
	gchar* _tmp100_;
	gchar* _tmp101_;
	gchar* _tmp102_;
	const gchar* _tmp103_ = NULL;
	gchar* _tmp104_ = NULL;
	gchar* _tmp105_;
	gchar* _tmp106_;
	gchar* _tmp107_;
	gchar* _tmp108_;
	gchar* _tmp109_;
	const gchar* _tmp110_;
	gchar* _tmp111_ = NULL;
	gchar* _tmp112_;
	gchar* _tmp113_;
	gchar* _tmp114_;
	gchar* _tmp115_;
	gchar* _tmp116_;
	const gchar* _tmp117_ = NULL;
	gchar* _tmp118_ = NULL;
	gchar* _tmp119_;
	gchar* _tmp120_;
	gchar* _tmp121_;
	gchar* _tmp122_;
	gchar* _tmp123_;
	gchar** _tmp124_;
	gint _tmp124__length1;
	const gchar* _tmp125_;
	gint _tmp126_ = 0;
	const gchar* _tmp127_;
	gchar* _tmp128_;
	gchar* _tmp129_;
	gchar* _tmp130_;
	gchar* _tmp131_;
	const gchar* _tmp132_ = NULL;
	gchar* _tmp133_ = NULL;
	gchar* _tmp134_;
	gchar* _tmp135_;
	gchar* _tmp136_;
	gchar* _tmp137_;
	gchar* _tmp138_;
	gchar** _tmp139_;
	gint _tmp139__length1;
	const gchar* _tmp140_;
	const gchar* _tmp141_ = NULL;
	gchar* _tmp142_;
	gchar* _tmp143_;
	gchar* _tmp144_;
	gchar* _tmp145_;
	const gchar* _tmp146_ = NULL;
	gchar* _tmp147_ = NULL;
	gchar* _tmp148_;
	gchar* _tmp149_;
	gchar* _tmp150_;
	gchar* _tmp151_;
	gchar* _tmp152_;
	gchar** _tmp153_;
	gint _tmp153__length1;
	const gchar* _tmp154_;
	gint _tmp155_ = 0;
	const gchar* _tmp156_;
	gchar* _tmp157_;
	gchar* _tmp158_;
	gchar* _tmp159_;
	gchar* _tmp160_;
	const gchar* _tmp161_ = NULL;
	gchar* _tmp162_ = NULL;
	gchar* _tmp163_;
	gchar* _tmp164_;
	gchar* _tmp165_;
	gchar* _tmp166_;
	gchar* _tmp167_;
	gchar** _tmp168_;
	gint _tmp168__length1;
	const gchar* _tmp169_;
	const gchar* _tmp170_ = NULL;
	gchar* _tmp171_;
	gchar* _tmp172_;
	gchar* _tmp173_;
	gchar* _tmp174_;
	const gchar* _tmp175_ = NULL;
	gchar* _tmp176_ = NULL;
	gchar* _tmp177_;
	gchar* _tmp178_;
	gchar* _tmp179_;
	gchar* _tmp180_;
	gchar* _tmp181_;
	gchar** _tmp182_;
	gint _tmp182__length1;
	const gchar* _tmp183_;
	gchar* _tmp184_;
	gchar* _tmp185_;
	gchar* _tmp186_;
	gchar* _tmp187_;
	gchar** _tmp188_;
	gint _tmp188__length1;
	const gchar* _tmp189_;
	gchar* _tmp190_;
	gchar* _tmp191_;
	gchar* _tmp192_;
	gchar* _tmp193_;
	const gchar* _tmp194_;
	gchar* _tmp195_ = NULL;
	gchar* _tmp196_;
	gchar* _tmp197_;
	gchar* _tmp198_;
	gchar* _tmp199_;
	gchar* _tmp200_;
	const gchar* _tmp201_ = NULL;
	gchar* _tmp202_ = NULL;
	gchar* _tmp203_;
	gchar* _tmp204_;
	gchar* _tmp205_;
	gchar* _tmp206_;
	gchar* _tmp207_;
	gchar** _tmp208_;
	gint _tmp208__length1;
	const gchar* _tmp209_;
	gchar* _tmp210_;
	gchar* _tmp211_;
	gchar* _tmp212_;
	gchar* _tmp213_;
	gchar** _tmp214_;
	gint _tmp214__length1;
	const gchar* _tmp215_;
	gchar* _tmp216_;
	gchar* _tmp217_;
	gchar* _tmp218_;
	gchar* _tmp219_;
	const gchar* _tmp220_;
	gchar* _tmp221_ = NULL;
	gchar* _tmp222_;
	gchar* _tmp223_;
	gchar* _tmp224_;
	gchar* _tmp225_;
	ShadowedLabel* _tmp226_;
	const gchar* _tmp227_;
	g_return_if_fail (session != NULL);
	g_return_if_fail (m != NULL);
	_tmp0_ = self->priv->message;
	_tmp1_ = _tmp0_->response_body;
	_tmp2_ = _tmp1_->data;
	_tmp2__length1 = (gint) _tmp1_->length;
	_tmp3_ = g_strdup ((const gchar*) _tmp2_);
	data = _tmp3_;
	_tmp4_ = data;
	if (_tmp4_ == NULL) {
		ShadowedLabel* _tmp5_;
		ShadowedLabel* _tmp6_;
		_tmp5_ = self->priv->label;
		clutter_actor_hide ((ClutterActor*) _tmp5_);
		_tmp6_ = self->priv->reload;
		clutter_actor_show ((ClutterActor*) _tmp6_);
		_g_free0 (data);
		return;
	}
	_tmp7_ = data;
	_tmp8_ = g_strdup ("temp");
	_tmp9_ = g_strdup ("text");
	_tmp10_ = g_strdup ("code");
	_tmp11_ = g_new0 (gchar*, 3 + 1);
	_tmp11_[0] = _tmp8_;
	_tmp11_[1] = _tmp9_;
	_tmp11_[2] = _tmp10_;
	_tmp12_ = _tmp11_;
	_tmp12__length1 = 3;
	_tmp14_ = weather_get_attributes (self, _tmp7_, "yweather:condition", _tmp12_, 3, 0, &_tmp13_);
	_tmp15_ = _tmp14_;
	_tmp15__length1 = _tmp13_;
	_tmp12_ = (_vala_array_free (_tmp12_, _tmp12__length1, (GDestroyNotify) g_free), NULL);
	current = _tmp15_;
	current_length1 = _tmp15__length1;
	_current_size_ = current_length1;
	_tmp16_ = data;
	_tmp17_ = g_strdup ("day");
	_tmp18_ = g_strdup ("date");
	_tmp19_ = g_strdup ("low");
	_tmp20_ = g_strdup ("high");
	_tmp21_ = g_strdup ("text");
	_tmp22_ = g_strdup ("code");
	_tmp23_ = g_new0 (gchar*, 6 + 1);
	_tmp23_[0] = _tmp17_;
	_tmp23_[1] = _tmp18_;
	_tmp23_[2] = _tmp19_;
	_tmp23_[3] = _tmp20_;
	_tmp23_[4] = _tmp21_;
	_tmp23_[5] = _tmp22_;
	_tmp24_ = _tmp23_;
	_tmp24__length1 = 6;
	_tmp25_ = data;
	_tmp26_ = string_index_of (_tmp25_, "<yweather:forecast", 0);
	_tmp28_ = weather_get_attributes (self, _tmp16_, "yweather:forecast", _tmp24_, 6, _tmp26_, &_tmp27_);
	_tmp29_ = _tmp28_;
	_tmp29__length1 = _tmp27_;
	_tmp24_ = (_vala_array_free (_tmp24_, _tmp24__length1, (GDestroyNotify) g_free), NULL);
	forecast = _tmp29_;
	forecast_length1 = _tmp29__length1;
	_forecast_size_ = forecast_length1;
	_tmp30_ = data;
	_tmp31_ = g_strdup ("day");
	_tmp32_ = g_strdup ("date");
	_tmp33_ = g_strdup ("low");
	_tmp34_ = g_strdup ("high");
	_tmp35_ = g_strdup ("text");
	_tmp36_ = g_strdup ("code");
	_tmp37_ = g_new0 (gchar*, 6 + 1);
	_tmp37_[0] = _tmp31_;
	_tmp37_[1] = _tmp32_;
	_tmp37_[2] = _tmp33_;
	_tmp37_[3] = _tmp34_;
	_tmp37_[4] = _tmp35_;
	_tmp37_[5] = _tmp36_;
	_tmp38_ = _tmp37_;
	_tmp38__length1 = 6;
	_tmp39_ = data;
	_tmp40_ = string_index_of (_tmp39_, "<yweather:forecast", 0);
	_tmp42_ = weather_get_attributes (self, _tmp30_, "yweather:forecast", _tmp38_, 6, _tmp40_ + 10, &_tmp41_);
	_tmp43_ = _tmp42_;
	_tmp43__length1 = _tmp41_;
	_tmp38_ = (_vala_array_free (_tmp38_, _tmp38__length1, (GDestroyNotify) g_free), NULL);
	forecast2 = _tmp43_;
	forecast2_length1 = _tmp43__length1;
	_forecast2_size_ = forecast2_length1;
	_tmp44_ = g_date_time_new_now_local ();
	_tmp45_ = _tmp44_;
	_tmp46_ = _ ("%A");
	_tmp47_ = g_date_time_format (_tmp45_, _tmp46_);
	_tmp48_ = _tmp47_;
	_g_date_time_unref0 (_tmp45_);
	today = _tmp48_;
	_tmp49_ = _ (textcolor);
	_tmp50_ = g_strdup_printf ("<span face='Open Sans Light' font='24' color='%s'", _tmp49_);
	_tmp51_ = _tmp50_;
	_tmp52_ = g_strconcat (_tmp51_, ">", NULL);
	_tmp53_ = _tmp52_;
	_tmp54_ = today;
	_tmp55_ = g_strconcat (_tmp53_, _tmp54_, NULL);
	_tmp56_ = _tmp55_;
	_tmp57_ = g_strconcat (_tmp56_, "</span>", NULL);
	_tmp58_ = _tmp57_;
	_tmp59_ = _ (textcolor);
	_tmp60_ = g_strdup_printf ("<span face='Open Sans Light' font='16' color='%s'", _tmp59_);
	_tmp61_ = _tmp60_;
	_tmp62_ = g_strconcat (_tmp58_, _tmp61_, NULL);
	_tmp63_ = _tmp62_;
	_tmp64_ = g_strconcat (_tmp63_, "> // <i>", NULL);
	_tmp65_ = _tmp64_;
	_tmp66_ = self->priv->condition_texts;
	_tmp66__length1 = self->priv->condition_texts_length1;
	_tmp67_ = current;
	_tmp67__length1 = current_length1;
	_tmp68_ = _tmp67_[2];
	_tmp69_ = atoi (_tmp68_);
	_tmp70_ = _tmp66_[_tmp69_];
	_tmp71_ = g_strconcat (_tmp65_, _tmp70_, NULL);
	_tmp72_ = _tmp71_;
	_tmp73_ = g_strconcat (_tmp72_, "</i></span>\n", NULL);
	_tmp74_ = _tmp73_;
	_tmp75_ = _ (textcolor);
	_tmp76_ = g_strdup_printf ("<span face='gazetteweather' font='68' color='%s'", _tmp75_);
	_tmp77_ = _tmp76_;
	_tmp78_ = g_strconcat (_tmp74_, _tmp77_, NULL);
	_tmp79_ = _tmp78_;
	_tmp80_ = g_strconcat (_tmp79_, ">", NULL);
	_tmp81_ = _tmp80_;
	_tmp82_ = current;
	_tmp82__length1 = current_length1;
	_tmp83_ = _tmp82_[2];
	_tmp84_ = atoi (_tmp83_);
	_tmp85_ = condition_codes[_tmp84_];
	_tmp86_ = g_strconcat (_tmp81_, _tmp85_, NULL);
	_tmp87_ = _tmp86_;
	_tmp88_ = g_strconcat (_tmp87_, "</span>", NULL);
	_tmp89_ = _tmp88_;
	_tmp90_ = _ (textcolor);
	_tmp91_ = g_strdup_printf ("<span face='Raleway' weight='100' font='72' color='%s'", _tmp90_);
	_tmp92_ = _tmp91_;
	_tmp93_ = g_strconcat (_tmp89_, _tmp92_, NULL);
	_tmp94_ = _tmp93_;
	_tmp95_ = g_strconcat (_tmp94_, "> ", NULL);
	_tmp96_ = _tmp95_;
	_tmp97_ = current;
	_tmp97__length1 = current_length1;
	_tmp98_ = _tmp97_[0];
	_tmp99_ = g_strconcat (_tmp96_, _tmp98_, NULL);
	_tmp100_ = _tmp99_;
	_tmp101_ = g_strconcat (_tmp100_, "</span>", NULL);
	_tmp102_ = _tmp101_;
	_tmp103_ = _ (textcolor);
	_tmp104_ = g_strdup_printf ("<span face='Raleway' weight='100' font='40' color='%s'", _tmp103_);
	_tmp105_ = _tmp104_;
	_tmp106_ = g_strconcat (_tmp102_, _tmp105_, NULL);
	_tmp107_ = _tmp106_;
	_tmp108_ = g_strconcat (_tmp107_, "> ° ", NULL);
	_tmp109_ = _tmp108_;
	_tmp110_ = self->priv->unit;
	_tmp111_ = g_utf8_strup (_tmp110_, (gssize) (-1));
	_tmp112_ = _tmp111_;
	_tmp113_ = g_strconcat (_tmp109_, _tmp112_, NULL);
	_tmp114_ = _tmp113_;
	_tmp115_ = g_strconcat (_tmp114_, "</span>\n", NULL);
	_tmp116_ = _tmp115_;
	_tmp117_ = _ (textcolor);
	_tmp118_ = g_strdup_printf ("<span face='gazetteweather' font='30' color='%s'", _tmp117_);
	_tmp119_ = _tmp118_;
	_tmp120_ = g_strconcat (_tmp116_, _tmp119_, NULL);
	_tmp121_ = _tmp120_;
	_tmp122_ = g_strconcat (_tmp121_, ">", NULL);
	_tmp123_ = _tmp122_;
	_tmp124_ = forecast;
	_tmp124__length1 = forecast_length1;
	_tmp125_ = _tmp124_[5];
	_tmp126_ = atoi (_tmp125_);
	_tmp127_ = condition_codes[_tmp126_];
	_tmp128_ = g_strconcat (_tmp123_, _tmp127_, NULL);
	_tmp129_ = _tmp128_;
	_tmp130_ = g_strconcat (_tmp129_, "</span>", NULL);
	_tmp131_ = _tmp130_;
	_tmp132_ = _ (textcolor);
	_tmp133_ = g_strdup_printf ("<span face='Open Sans Light' font='26' color='%s'", _tmp132_);
	_tmp134_ = _tmp133_;
	_tmp135_ = g_strconcat (_tmp131_, _tmp134_, NULL);
	_tmp136_ = _tmp135_;
	_tmp137_ = g_strconcat (_tmp136_, "> ", NULL);
	_tmp138_ = _tmp137_;
	_tmp139_ = forecast;
	_tmp139__length1 = forecast_length1;
	_tmp140_ = _tmp139_[0];
	_tmp141_ = _ (_tmp140_);
	_tmp142_ = g_strconcat (_tmp138_, _tmp141_, NULL);
	_tmp143_ = _tmp142_;
	_tmp144_ = g_strconcat (_tmp143_, "     </span>", NULL);
	_tmp145_ = _tmp144_;
	_tmp146_ = _ (textcolor);
	_tmp147_ = g_strdup_printf ("<span face='gazetteweather' font='30' color='%s'", _tmp146_);
	_tmp148_ = _tmp147_;
	_tmp149_ = g_strconcat (_tmp145_, _tmp148_, NULL);
	_tmp150_ = _tmp149_;
	_tmp151_ = g_strconcat (_tmp150_, ">", NULL);
	_tmp152_ = _tmp151_;
	_tmp153_ = forecast2;
	_tmp153__length1 = forecast2_length1;
	_tmp154_ = _tmp153_[5];
	_tmp155_ = atoi (_tmp154_);
	_tmp156_ = condition_codes[_tmp155_];
	_tmp157_ = g_strconcat (_tmp152_, _tmp156_, NULL);
	_tmp158_ = _tmp157_;
	_tmp159_ = g_strconcat (_tmp158_, "</span>", NULL);
	_tmp160_ = _tmp159_;
	_tmp161_ = _ (textcolor);
	_tmp162_ = g_strdup_printf ("<span face='Open Sans Light' font='26' color='%s'", _tmp161_);
	_tmp163_ = _tmp162_;
	_tmp164_ = g_strconcat (_tmp160_, _tmp163_, NULL);
	_tmp165_ = _tmp164_;
	_tmp166_ = g_strconcat (_tmp165_, "> ", NULL);
	_tmp167_ = _tmp166_;
	_tmp168_ = forecast2;
	_tmp168__length1 = forecast2_length1;
	_tmp169_ = _tmp168_[0];
	_tmp170_ = _ (_tmp169_);
	_tmp171_ = g_strconcat (_tmp167_, _tmp170_, NULL);
	_tmp172_ = _tmp171_;
	_tmp173_ = g_strconcat (_tmp172_, "</span>\n", NULL);
	_tmp174_ = _tmp173_;
	_tmp175_ = _ (textcolor);
	_tmp176_ = g_strdup_printf ("<span face='Raleway' font='21' color='%s'", _tmp175_);
	_tmp177_ = _tmp176_;
	_tmp178_ = g_strconcat (_tmp174_, _tmp177_, NULL);
	_tmp179_ = _tmp178_;
	_tmp180_ = g_strconcat (_tmp179_, ">", NULL);
	_tmp181_ = _tmp180_;
	_tmp182_ = forecast;
	_tmp182__length1 = forecast_length1;
	_tmp183_ = _tmp182_[2];
	_tmp184_ = g_strconcat (_tmp181_, _tmp183_, NULL);
	_tmp185_ = _tmp184_;
	_tmp186_ = g_strconcat (_tmp185_, " - ", NULL);
	_tmp187_ = _tmp186_;
	_tmp188_ = forecast;
	_tmp188__length1 = forecast_length1;
	_tmp189_ = _tmp188_[3];
	_tmp190_ = g_strconcat (_tmp187_, _tmp189_, NULL);
	_tmp191_ = _tmp190_;
	_tmp192_ = g_strconcat (_tmp191_, "°", NULL);
	_tmp193_ = _tmp192_;
	_tmp194_ = self->priv->unit;
	_tmp195_ = g_utf8_strup (_tmp194_, (gssize) (-1));
	_tmp196_ = _tmp195_;
	_tmp197_ = g_strconcat (_tmp193_, _tmp196_, NULL);
	_tmp198_ = _tmp197_;
	_tmp199_ = g_strconcat (_tmp198_, "      </span>", NULL);
	_tmp200_ = _tmp199_;
	_tmp201_ = _ (textcolor);
	_tmp202_ = g_strdup_printf ("<span face='Raleway' font='21' color='%s'", _tmp201_);
	_tmp203_ = _tmp202_;
	_tmp204_ = g_strconcat (_tmp200_, _tmp203_, NULL);
	_tmp205_ = _tmp204_;
	_tmp206_ = g_strconcat (_tmp205_, ">", NULL);
	_tmp207_ = _tmp206_;
	_tmp208_ = forecast2;
	_tmp208__length1 = forecast2_length1;
	_tmp209_ = _tmp208_[2];
	_tmp210_ = g_strconcat (_tmp207_, _tmp209_, NULL);
	_tmp211_ = _tmp210_;
	_tmp212_ = g_strconcat (_tmp211_, " - ", NULL);
	_tmp213_ = _tmp212_;
	_tmp214_ = forecast2;
	_tmp214__length1 = forecast2_length1;
	_tmp215_ = _tmp214_[3];
	_tmp216_ = g_strconcat (_tmp213_, _tmp215_, NULL);
	_tmp217_ = _tmp216_;
	_tmp218_ = g_strconcat (_tmp217_, "°", NULL);
	_tmp219_ = _tmp218_;
	_tmp220_ = self->priv->unit;
	_tmp221_ = g_utf8_strup (_tmp220_, (gssize) (-1));
	_tmp222_ = _tmp221_;
	_tmp223_ = g_strconcat (_tmp219_, _tmp222_, NULL);
	_tmp224_ = _tmp223_;
	_tmp225_ = g_strconcat (_tmp224_, "      </span>", NULL);
	_g_free0 (self->priv->text);
	self->priv->text = _tmp225_;
	_g_free0 (_tmp224_);
	_g_free0 (_tmp222_);
	_g_free0 (_tmp219_);
	_g_free0 (_tmp217_);
	_g_free0 (_tmp213_);
	_g_free0 (_tmp211_);
	_g_free0 (_tmp207_);
	_g_free0 (_tmp205_);
	_g_free0 (_tmp203_);
	_g_free0 (_tmp200_);
	_g_free0 (_tmp198_);
	_g_free0 (_tmp196_);
	_g_free0 (_tmp193_);
	_g_free0 (_tmp191_);
	_g_free0 (_tmp187_);
	_g_free0 (_tmp185_);
	_g_free0 (_tmp181_);
	_g_free0 (_tmp179_);
	_g_free0 (_tmp177_);
	_g_free0 (_tmp174_);
	_g_free0 (_tmp172_);
	_g_free0 (_tmp167_);
	_g_free0 (_tmp165_);
	_g_free0 (_tmp163_);
	_g_free0 (_tmp160_);
	_g_free0 (_tmp158_);
	_g_free0 (_tmp152_);
	_g_free0 (_tmp150_);
	_g_free0 (_tmp148_);
	_g_free0 (_tmp145_);
	_g_free0 (_tmp143_);
	_g_free0 (_tmp138_);
	_g_free0 (_tmp136_);
	_g_free0 (_tmp134_);
	_g_free0 (_tmp131_);
	_g_free0 (_tmp129_);
	_g_free0 (_tmp123_);
	_g_free0 (_tmp121_);
	_g_free0 (_tmp119_);
	_g_free0 (_tmp116_);
	_g_free0 (_tmp114_);
	_g_free0 (_tmp112_);
	_g_free0 (_tmp109_);
	_g_free0 (_tmp107_);
	_g_free0 (_tmp105_);
	_g_free0 (_tmp102_);
	_g_free0 (_tmp100_);
	_g_free0 (_tmp96_);
	_g_free0 (_tmp94_);
	_g_free0 (_tmp92_);
	_g_free0 (_tmp89_);
	_g_free0 (_tmp87_);
	_g_free0 (_tmp81_);
	_g_free0 (_tmp79_);
	_g_free0 (_tmp77_);
	_g_free0 (_tmp74_);
	_g_free0 (_tmp72_);
	_g_free0 (_tmp65_);
	_g_free0 (_tmp63_);
	_g_free0 (_tmp61_);
	_g_free0 (_tmp58_);
	_g_free0 (_tmp56_);
	_g_free0 (_tmp53_);
	_g_free0 (_tmp51_);
	_tmp226_ = self->priv->label;
	_tmp227_ = self->priv->text;
	shadowed_label_set_label (_tmp226_, _tmp227_);
	_g_free0 (today);
	forecast2 = (_vala_array_free (forecast2, forecast2_length1, (GDestroyNotify) g_free), NULL);
	forecast = (_vala_array_free (forecast, forecast_length1, (GDestroyNotify) g_free), NULL);
	current = (_vala_array_free (current, current_length1, (GDestroyNotify) g_free), NULL);
	_g_free0 (data);
}


static void ___lambda13__soup_session_callback (SoupSession* session, SoupMessage* msg, gpointer self) {
	__lambda13_ (self, session, msg);
}


static gboolean weather_real_update (Service* base) {
	Weather * self;
	gboolean result = FALSE;
	ShadowedLabel* _tmp0_;
	ShadowedLabel* _tmp1_;
	const gchar* _tmp2_ = NULL;
	gchar* _tmp3_ = NULL;
	gchar* _tmp4_;
	gchar* _tmp5_;
	gchar* _tmp6_;
	const gchar* _tmp7_ = NULL;
	gchar* _tmp8_;
	gchar* _tmp9_;
	gchar* _tmp10_;
	gchar* _tmp11_;
	ShadowedLabel* _tmp12_;
	GSettings* _tmp13_;
	gint _tmp14_ = 0;
	gchar* _tmp15_ = NULL;
	gchar* id;
	const gchar* _tmp16_ = NULL;
	GSettings* _tmp17_;
	gchar* _tmp18_ = NULL;
	gchar* _tmp19_;
	gboolean _tmp20_;
	const gchar* _tmp21_;
	gchar* _tmp22_;
	gchar* _tmp23_;
	gchar* url;
	const gchar* _tmp24_;
	const gchar* _tmp25_;
	gchar* _tmp26_;
	gchar* _tmp27_;
	gchar* _tmp28_;
	const gchar* _tmp29_;
	const gchar* _tmp30_;
	gchar* _tmp31_;
	gchar* _tmp32_;
	gchar* _tmp33_;
	const gchar* _tmp34_;
	SoupMessage* _tmp35_;
	SoupSessionAsync* _tmp36_;
	SoupMessage* _tmp37_;
	SoupMessage* _tmp38_;
	self = (Weather*) base;
	g_debug ("Weather.vala:167: Updating Weather");
	_tmp0_ = self->priv->reload;
	clutter_actor_hide ((ClutterActor*) _tmp0_);
	_tmp1_ = self->priv->label;
	_tmp2_ = _ (textcolor);
	_tmp3_ = g_strdup_printf ("<span face='Open Sans Light' font='16'  color='%s'", _tmp2_);
	_tmp4_ = _tmp3_;
	_tmp5_ = g_strconcat (_tmp4_, ">", NULL);
	_tmp6_ = _tmp5_;
	_tmp7_ = _ ("Loading weather,\nplease wait.");
	_tmp8_ = g_strconcat (_tmp6_, _tmp7_, NULL);
	_tmp9_ = _tmp8_;
	_tmp10_ = g_strconcat (_tmp9_, "</span>", NULL);
	_tmp11_ = _tmp10_;
	shadowed_label_set_label (_tmp1_, _tmp11_);
	_g_free0 (_tmp11_);
	_g_free0 (_tmp9_);
	_g_free0 (_tmp6_);
	_g_free0 (_tmp4_);
	_tmp12_ = self->priv->label;
	clutter_actor_show ((ClutterActor*) _tmp12_);
	_tmp13_ = self->priv->settings;
	_tmp14_ = g_settings_get_int (_tmp13_, "weather-id");
	_tmp15_ = g_strdup_printf ("%i", _tmp14_);
	id = _tmp15_;
	_tmp17_ = self->priv->settings;
	_tmp18_ = g_settings_get_string (_tmp17_, "weather-unit");
	_tmp19_ = _tmp18_;
	_tmp20_ = g_strcmp0 (_tmp19_, "Fahrenheit") == 0;
	_g_free0 (_tmp19_);
	if (_tmp20_) {
		_tmp16_ = "f";
	} else {
		_tmp16_ = "c";
	}
	_tmp21_ = _tmp16_;
	_tmp22_ = g_strdup (_tmp21_);
	_g_free0 (self->priv->unit);
	self->priv->unit = _tmp22_;
	_tmp23_ = g_strdup ("http://weather.yahooapis.com/forecastrss");
	url = _tmp23_;
	_tmp24_ = url;
	_tmp25_ = self->priv->unit;
	_tmp26_ = g_strconcat ("?u=", _tmp25_, NULL);
	_tmp27_ = _tmp26_;
	_tmp28_ = g_strconcat (_tmp24_, _tmp27_, NULL);
	_g_free0 (url);
	url = _tmp28_;
	_g_free0 (_tmp27_);
	_tmp29_ = url;
	_tmp30_ = id;
	_tmp31_ = g_strconcat ("&w=", _tmp30_, NULL);
	_tmp32_ = _tmp31_;
	_tmp33_ = g_strconcat (_tmp29_, _tmp32_, NULL);
	_g_free0 (url);
	url = _tmp33_;
	_g_free0 (_tmp32_);
	_tmp34_ = url;
	_tmp35_ = soup_message_new ("GET", _tmp34_);
	_g_object_unref0 (self->priv->message);
	self->priv->message = _tmp35_;
	_tmp36_ = self->priv->session;
	_tmp37_ = self->priv->message;
	_tmp38_ = _g_object_ref0 (_tmp37_);
	soup_session_queue_message ((SoupSession*) _tmp36_, _tmp38_, ___lambda13__soup_session_callback, self);
	result = TRUE;
	_g_free0 (url);
	_g_free0 (id);
	return result;
}


static void weather_class_init (WeatherClass * klass) {
	weather_parent_class = g_type_class_peek_parent (klass);
	g_type_class_add_private (klass, sizeof (WeatherPrivate));
	SERVICE_CLASS (klass)->create = weather_real_create;
	SERVICE_CLASS (klass)->update = weather_real_update;
	G_OBJECT_CLASS (klass)->finalize = weather_finalize;
}


static void weather_instance_init (Weather * self) {
	const gchar* _tmp0_ = NULL;
	gchar* _tmp1_;
	const gchar* _tmp2_ = NULL;
	gchar* _tmp3_;
	const gchar* _tmp4_ = NULL;
	gchar* _tmp5_;
	const gchar* _tmp6_ = NULL;
	gchar* _tmp7_;
	const gchar* _tmp8_ = NULL;
	gchar* _tmp9_;
	const gchar* _tmp10_ = NULL;
	gchar* _tmp11_;
	const gchar* _tmp12_ = NULL;
	gchar* _tmp13_;
	const gchar* _tmp14_ = NULL;
	gchar* _tmp15_;
	const gchar* _tmp16_ = NULL;
	gchar* _tmp17_;
	const gchar* _tmp18_ = NULL;
	gchar* _tmp19_;
	const gchar* _tmp20_ = NULL;
	gchar* _tmp21_;
	const gchar* _tmp22_ = NULL;
	gchar* _tmp23_;
	const gchar* _tmp24_ = NULL;
	gchar* _tmp25_;
	const gchar* _tmp26_ = NULL;
	gchar* _tmp27_;
	const gchar* _tmp28_ = NULL;
	gchar* _tmp29_;
	const gchar* _tmp30_ = NULL;
	gchar* _tmp31_;
	const gchar* _tmp32_ = NULL;
	gchar* _tmp33_;
	const gchar* _tmp34_ = NULL;
	gchar* _tmp35_;
	const gchar* _tmp36_ = NULL;
	gchar* _tmp37_;
	const gchar* _tmp38_ = NULL;
	gchar* _tmp39_;
	const gchar* _tmp40_ = NULL;
	gchar* _tmp41_;
	const gchar* _tmp42_ = NULL;
	gchar* _tmp43_;
	const gchar* _tmp44_ = NULL;
	gchar* _tmp45_;
	const gchar* _tmp46_ = NULL;
	gchar* _tmp47_;
	const gchar* _tmp48_ = NULL;
	gchar* _tmp49_;
	const gchar* _tmp50_ = NULL;
	gchar* _tmp51_;
	const gchar* _tmp52_ = NULL;
	gchar* _tmp53_;
	const gchar* _tmp54_ = NULL;
	gchar* _tmp55_;
	const gchar* _tmp56_ = NULL;
	gchar* _tmp57_;
	const gchar* _tmp58_ = NULL;
	gchar* _tmp59_;
	const gchar* _tmp60_ = NULL;
	gchar* _tmp61_;
	const gchar* _tmp62_ = NULL;
	gchar* _tmp63_;
	const gchar* _tmp64_ = NULL;
	gchar* _tmp65_;
	const gchar* _tmp66_ = NULL;
	gchar* _tmp67_;
	const gchar* _tmp68_ = NULL;
	gchar* _tmp69_;
	const gchar* _tmp70_ = NULL;
	gchar* _tmp71_;
	const gchar* _tmp72_ = NULL;
	gchar* _tmp73_;
	const gchar* _tmp74_ = NULL;
	gchar* _tmp75_;
	const gchar* _tmp76_ = NULL;
	gchar* _tmp77_;
	const gchar* _tmp78_ = NULL;
	gchar* _tmp79_;
	const gchar* _tmp80_ = NULL;
	gchar* _tmp81_;
	const gchar* _tmp82_ = NULL;
	gchar* _tmp83_;
	const gchar* _tmp84_ = NULL;
	gchar* _tmp85_;
	const gchar* _tmp86_ = NULL;
	gchar* _tmp87_;
	const gchar* _tmp88_ = NULL;
	gchar* _tmp89_;
	const gchar* _tmp90_ = NULL;
	gchar* _tmp91_;
	const gchar* _tmp92_ = NULL;
	gchar* _tmp93_;
	const gchar* _tmp94_ = NULL;
	gchar* _tmp95_;
	const gchar* _tmp96_ = NULL;
	gchar* _tmp97_;
	gchar** _tmp98_ = NULL;
	const gchar* _tmp99_ = NULL;
	gchar* _tmp100_;
	const gchar* _tmp101_ = NULL;
	gchar* _tmp102_;
	const gchar* _tmp103_ = NULL;
	gchar* _tmp104_;
	const gchar* _tmp105_ = NULL;
	gchar* _tmp106_;
	const gchar* _tmp107_ = NULL;
	gchar* _tmp108_;
	const gchar* _tmp109_ = NULL;
	gchar* _tmp110_;
	const gchar* _tmp111_ = NULL;
	gchar* _tmp112_;
	gchar** _tmp113_ = NULL;
	self->priv = WEATHER_GET_PRIVATE (self);
	_tmp0_ = _ ("Tornado");
	_tmp1_ = g_strdup (_tmp0_);
	_tmp2_ = _ ("Tropical storm");
	_tmp3_ = g_strdup (_tmp2_);
	_tmp4_ = _ ("Hurricane");
	_tmp5_ = g_strdup (_tmp4_);
	_tmp6_ = _ ("Severe thunderstorms");
	_tmp7_ = g_strdup (_tmp6_);
	_tmp8_ = _ ("Thunderstorms");
	_tmp9_ = g_strdup (_tmp8_);
	_tmp10_ = _ ("Mixed rain and snow");
	_tmp11_ = g_strdup (_tmp10_);
	_tmp12_ = _ ("Mixed rain and sleet");
	_tmp13_ = g_strdup (_tmp12_);
	_tmp14_ = _ ("Mixed snow and sleet");
	_tmp15_ = g_strdup (_tmp14_);
	_tmp16_ = _ ("Freezing drizzle");
	_tmp17_ = g_strdup (_tmp16_);
	_tmp18_ = _ ("Drizzle");
	_tmp19_ = g_strdup (_tmp18_);
	_tmp20_ = _ ("Freezing rain");
	_tmp21_ = g_strdup (_tmp20_);
	_tmp22_ = _ ("Showers");
	_tmp23_ = g_strdup (_tmp22_);
	_tmp24_ = _ ("Showers");
	_tmp25_ = g_strdup (_tmp24_);
	_tmp26_ = _ ("Snow flurries");
	_tmp27_ = g_strdup (_tmp26_);
	_tmp28_ = _ ("Light snow showers");
	_tmp29_ = g_strdup (_tmp28_);
	_tmp30_ = _ ("Blowing snow");
	_tmp31_ = g_strdup (_tmp30_);
	_tmp32_ = _ ("Snow");
	_tmp33_ = g_strdup (_tmp32_);
	_tmp34_ = _ ("Hail");
	_tmp35_ = g_strdup (_tmp34_);
	_tmp36_ = _ ("Sleet");
	_tmp37_ = g_strdup (_tmp36_);
	_tmp38_ = _ ("Dust");
	_tmp39_ = g_strdup (_tmp38_);
	_tmp40_ = _ ("Foggy");
	_tmp41_ = g_strdup (_tmp40_);
	_tmp42_ = _ ("Haze");
	_tmp43_ = g_strdup (_tmp42_);
	_tmp44_ = _ ("Smoky");
	_tmp45_ = g_strdup (_tmp44_);
	_tmp46_ = _ ("Blustery");
	_tmp47_ = g_strdup (_tmp46_);
	_tmp48_ = _ ("Windy");
	_tmp49_ = g_strdup (_tmp48_);
	_tmp50_ = _ ("Cold");
	_tmp51_ = g_strdup (_tmp50_);
	_tmp52_ = _ ("Cloudy");
	_tmp53_ = g_strdup (_tmp52_);
	_tmp54_ = _ ("Mostly cloudy");
	_tmp55_ = g_strdup (_tmp54_);
	_tmp56_ = _ ("Mostly cloudy");
	_tmp57_ = g_strdup (_tmp56_);
	_tmp58_ = _ ("Partly cloudy");
	_tmp59_ = g_strdup (_tmp58_);
	_tmp60_ = _ ("Partly cloudy");
	_tmp61_ = g_strdup (_tmp60_);
	_tmp62_ = _ ("Clear");
	_tmp63_ = g_strdup (_tmp62_);
	_tmp64_ = _ ("Sunny");
	_tmp65_ = g_strdup (_tmp64_);
	_tmp66_ = _ ("Fair");
	_tmp67_ = g_strdup (_tmp66_);
	_tmp68_ = _ ("Fair");
	_tmp69_ = g_strdup (_tmp68_);
	_tmp70_ = _ ("Mixed rain and hail");
	_tmp71_ = g_strdup (_tmp70_);
	_tmp72_ = _ ("Hot");
	_tmp73_ = g_strdup (_tmp72_);
	_tmp74_ = _ ("Isolated thunderstorms");
	_tmp75_ = g_strdup (_tmp74_);
	_tmp76_ = _ ("Scattered thunderstorms");
	_tmp77_ = g_strdup (_tmp76_);
	_tmp78_ = _ ("Scattered thunderstorms");
	_tmp79_ = g_strdup (_tmp78_);
	_tmp80_ = _ ("Scattered showers");
	_tmp81_ = g_strdup (_tmp80_);
	_tmp82_ = _ ("Heavy snow");
	_tmp83_ = g_strdup (_tmp82_);
	_tmp84_ = _ ("Scattered snow showers");
	_tmp85_ = g_strdup (_tmp84_);
	_tmp86_ = _ ("Heavy snow");
	_tmp87_ = g_strdup (_tmp86_);
	_tmp88_ = _ ("Partly cloudy");
	_tmp89_ = g_strdup (_tmp88_);
	_tmp90_ = _ ("Thundershowers");
	_tmp91_ = g_strdup (_tmp90_);
	_tmp92_ = _ ("Snow showers");
	_tmp93_ = g_strdup (_tmp92_);
	_tmp94_ = _ ("Isolated thundershowers");
	_tmp95_ = g_strdup (_tmp94_);
	_tmp96_ = _ ("Not available");
	_tmp97_ = g_strdup (_tmp96_);
	_tmp98_ = g_new0 (gchar*, 49 + 1);
	_tmp98_[0] = _tmp1_;
	_tmp98_[1] = _tmp3_;
	_tmp98_[2] = _tmp5_;
	_tmp98_[3] = _tmp7_;
	_tmp98_[4] = _tmp9_;
	_tmp98_[5] = _tmp11_;
	_tmp98_[6] = _tmp13_;
	_tmp98_[7] = _tmp15_;
	_tmp98_[8] = _tmp17_;
	_tmp98_[9] = _tmp19_;
	_tmp98_[10] = _tmp21_;
	_tmp98_[11] = _tmp23_;
	_tmp98_[12] = _tmp25_;
	_tmp98_[13] = _tmp27_;
	_tmp98_[14] = _tmp29_;
	_tmp98_[15] = _tmp31_;
	_tmp98_[16] = _tmp33_;
	_tmp98_[17] = _tmp35_;
	_tmp98_[18] = _tmp37_;
	_tmp98_[19] = _tmp39_;
	_tmp98_[20] = _tmp41_;
	_tmp98_[21] = _tmp43_;
	_tmp98_[22] = _tmp45_;
	_tmp98_[23] = _tmp47_;
	_tmp98_[24] = _tmp49_;
	_tmp98_[25] = _tmp51_;
	_tmp98_[26] = _tmp53_;
	_tmp98_[27] = _tmp55_;
	_tmp98_[28] = _tmp57_;
	_tmp98_[29] = _tmp59_;
	_tmp98_[30] = _tmp61_;
	_tmp98_[31] = _tmp63_;
	_tmp98_[32] = _tmp65_;
	_tmp98_[33] = _tmp67_;
	_tmp98_[34] = _tmp69_;
	_tmp98_[35] = _tmp71_;
	_tmp98_[36] = _tmp73_;
	_tmp98_[37] = _tmp75_;
	_tmp98_[38] = _tmp77_;
	_tmp98_[39] = _tmp79_;
	_tmp98_[40] = _tmp81_;
	_tmp98_[41] = _tmp83_;
	_tmp98_[42] = _tmp85_;
	_tmp98_[43] = _tmp87_;
	_tmp98_[44] = _tmp89_;
	_tmp98_[45] = _tmp91_;
	_tmp98_[46] = _tmp93_;
	_tmp98_[47] = _tmp95_;
	_tmp98_[48] = _tmp97_;
	self->priv->condition_texts = _tmp98_;
	self->priv->condition_texts_length1 = 49;
	self->priv->_condition_texts_size_ = self->priv->condition_texts_length1;
	_tmp99_ = _ ("Mon");
	_tmp100_ = g_strdup (_tmp99_);
	_tmp101_ = _ ("Tue");
	_tmp102_ = g_strdup (_tmp101_);
	_tmp103_ = _ ("Wed");
	_tmp104_ = g_strdup (_tmp103_);
	_tmp105_ = _ ("Thu");
	_tmp106_ = g_strdup (_tmp105_);
	_tmp107_ = _ ("Fri");
	_tmp108_ = g_strdup (_tmp107_);
	_tmp109_ = _ ("Sat");
	_tmp110_ = g_strdup (_tmp109_);
	_tmp111_ = _ ("Sun");
	_tmp112_ = g_strdup (_tmp111_);
	_tmp113_ = g_new0 (gchar*, 7 + 1);
	_tmp113_[0] = _tmp100_;
	_tmp113_[1] = _tmp102_;
	_tmp113_[2] = _tmp104_;
	_tmp113_[3] = _tmp106_;
	_tmp113_[4] = _tmp108_;
	_tmp113_[5] = _tmp110_;
	_tmp113_[6] = _tmp112_;
	self->priv->day_texts = _tmp113_;
	self->priv->day_texts_length1 = 7;
	self->priv->_day_texts_size_ = self->priv->day_texts_length1;
}


static void weather_finalize (GObject* obj) {
	Weather * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, TYPE_WEATHER, Weather);
	self->priv->condition_texts = (_vala_array_free (self->priv->condition_texts, self->priv->condition_texts_length1, (GDestroyNotify) g_free), NULL);
	self->priv->day_texts = (_vala_array_free (self->priv->day_texts, self->priv->day_texts_length1, (GDestroyNotify) g_free), NULL);
	_g_free0 (self->priv->unit);
	_g_free0 (self->priv->text);
	_g_object_unref0 (self->priv->session);
	_g_object_unref0 (self->priv->message);
	_g_object_unref0 (self->priv->settings);
	_g_object_unref0 (self->priv->label);
	_g_object_unref0 (self->priv->reload);
	G_OBJECT_CLASS (weather_parent_class)->finalize (obj);
}


GType weather_get_type (void) {
	static volatile gsize weather_type_id__volatile = 0;
	if (g_once_init_enter (&weather_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (WeatherClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) weather_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (Weather), 0, (GInstanceInitFunc) weather_instance_init, NULL };
		GType weather_type_id;
		weather_type_id = g_type_register_static (TYPE_SERVICE, "Weather", &g_define_type_info, 0);
		g_once_init_leave (&weather_type_id__volatile, weather_type_id);
	}
	return weather_type_id__volatile;
}


static void _vala_array_destroy (gpointer array, gint array_length, GDestroyNotify destroy_func) {
	if ((array != NULL) && (destroy_func != NULL)) {
		int i;
		for (i = 0; i < array_length; i = i + 1) {
			if (((gpointer*) array)[i] != NULL) {
				destroy_func (((gpointer*) array)[i]);
			}
		}
	}
}


static void _vala_array_free (gpointer array, gint array_length, GDestroyNotify destroy_func) {
	_vala_array_destroy (array, array_length, destroy_func);
	g_free (array);
}



