/* main.c generated by valac 0.20.1, the Vala compiler
 * generated from main.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <pantheon.h>
#include <gtk/gtk.h>
#include <glib/gi18n-lib.h>
#include <pango/pango.h>
#include <gio/gio.h>
#include <stdlib.h>
#include <string.h>


#define TYPE_GAZETTE_SETTINGS (gazette_settings_get_type ())
#define GAZETTE_SETTINGS(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_GAZETTE_SETTINGS, GazetteSettings))
#define GAZETTE_SETTINGS_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_GAZETTE_SETTINGS, GazetteSettingsClass))
#define IS_GAZETTE_SETTINGS(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_GAZETTE_SETTINGS))
#define IS_GAZETTE_SETTINGS_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_GAZETTE_SETTINGS))
#define GAZETTE_SETTINGS_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_GAZETTE_SETTINGS, GazetteSettingsClass))

typedef struct _GazetteSettings GazetteSettings;
typedef struct _GazetteSettingsClass GazetteSettingsClass;
typedef struct _GazetteSettingsPrivate GazetteSettingsPrivate;

#define GAZETTE_TYPE_SERVICE (gazette_service_get_type ())
#define GAZETTE_SERVICE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), GAZETTE_TYPE_SERVICE, GazetteService))
#define GAZETTE_SERVICE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), GAZETTE_TYPE_SERVICE, GazetteServiceClass))
#define GAZETTE_IS_SERVICE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), GAZETTE_TYPE_SERVICE))
#define GAZETTE_IS_SERVICE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), GAZETTE_TYPE_SERVICE))
#define GAZETTE_SERVICE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), GAZETTE_TYPE_SERVICE, GazetteServiceClass))

typedef struct _GazetteService GazetteService;
typedef struct _GazetteServiceClass GazetteServiceClass;
#define __g_list_free__g_object_unref0_0(var) ((var == NULL) ? NULL : (var = (_g_list_free__g_object_unref0_ (var), NULL)))
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
typedef struct _Block1Data Block1Data;

#define GAZETTE_TYPE_WEATHER (gazette_weather_get_type ())
#define GAZETTE_WEATHER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), GAZETTE_TYPE_WEATHER, GazetteWeather))
#define GAZETTE_WEATHER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), GAZETTE_TYPE_WEATHER, GazetteWeatherClass))
#define GAZETTE_IS_WEATHER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), GAZETTE_TYPE_WEATHER))
#define GAZETTE_IS_WEATHER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), GAZETTE_TYPE_WEATHER))
#define GAZETTE_WEATHER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), GAZETTE_TYPE_WEATHER, GazetteWeatherClass))

typedef struct _GazetteWeather GazetteWeather;
typedef struct _GazetteWeatherClass GazetteWeatherClass;

#define GAZETTE_TYPE_RECENT_FILES (gazette_recent_files_get_type ())
#define GAZETTE_RECENT_FILES(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), GAZETTE_TYPE_RECENT_FILES, GazetteRecentFiles))
#define GAZETTE_RECENT_FILES_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), GAZETTE_TYPE_RECENT_FILES, GazetteRecentFilesClass))
#define GAZETTE_IS_RECENT_FILES(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), GAZETTE_TYPE_RECENT_FILES))
#define GAZETTE_IS_RECENT_FILES_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), GAZETTE_TYPE_RECENT_FILES))
#define GAZETTE_RECENT_FILES_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), GAZETTE_TYPE_RECENT_FILES, GazetteRecentFilesClass))

typedef struct _GazetteRecentFiles GazetteRecentFiles;
typedef struct _GazetteRecentFilesClass GazetteRecentFilesClass;

#define GAZETTE_TYPE_RSS (gazette_rss_get_type ())
#define GAZETTE_RSS(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), GAZETTE_TYPE_RSS, GazetteRSS))
#define GAZETTE_RSS_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), GAZETTE_TYPE_RSS, GazetteRSSClass))
#define GAZETTE_IS_RSS(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), GAZETTE_TYPE_RSS))
#define GAZETTE_IS_RSS_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), GAZETTE_TYPE_RSS))
#define GAZETTE_RSS_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), GAZETTE_TYPE_RSS, GazetteRSSClass))

typedef struct _GazetteRSS GazetteRSS;
typedef struct _GazetteRSSClass GazetteRSSClass;
#define __vala_PangoFontDescription_free0(var) ((var == NULL) ? NULL : (var = (_vala_PangoFontDescription_free (var), NULL)))
typedef struct _GazetteServicePrivate GazetteServicePrivate;
#define _g_free0(var) (var = (g_free (var), NULL))
#define __vala_PangoAttrList_free0(var) ((var == NULL) ? NULL : (var = (_vala_PangoAttrList_free (var), NULL)))

struct _GazetteSettings {
	PantheonSwitchboardPlug parent_instance;
	GazetteSettingsPrivate * priv;
};

struct _GazetteSettingsClass {
	PantheonSwitchboardPlugClass parent_class;
};

struct _GazetteSettingsPrivate {
	GList* services;
	GazetteService* current;
};

struct _Block1Data {
	int _ref_count_;
	GazetteSettings * self;
	GtkBox* view;
	GtkLabel* cur_label;
	GtkImage* cur_image;
};

struct _GazetteService {
	GObject parent_instance;
	GazetteServicePrivate * priv;
	GtkGrid* container;
	GtkEventBox* item;
	GtkImage* icon;
	GtkSwitch* toggle;
	GtkLabel* name;
};

struct _GazetteServiceClass {
	GObjectClass parent_class;
	void (*run) (GazetteService* self, GFile* file);
};


static gpointer gazette_settings_parent_class = NULL;

GType gazette_settings_get_type (void) G_GNUC_CONST;
GType gazette_service_get_type (void) G_GNUC_CONST;
#define GAZETTE_SETTINGS_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), TYPE_GAZETTE_SETTINGS, GazetteSettingsPrivate))
enum  {
	GAZETTE_SETTINGS_DUMMY_PROPERTY
};
static void _g_object_unref0_ (gpointer var);
static void _g_list_free__g_object_unref0_ (GList* self);
GazetteSettings* gazette_settings_new (void);
GazetteSettings* gazette_settings_construct (GType object_type);
static Block1Data* block1_data_ref (Block1Data* _data1_);
static void block1_data_unref (void * _userdata_);
GazetteWeather* gazette_weather_new (void);
GazetteWeather* gazette_weather_construct (GType object_type);
GType gazette_weather_get_type (void) G_GNUC_CONST;
GazetteRecentFiles* gazette_recent_files_new (void);
GazetteRecentFiles* gazette_recent_files_construct (GType object_type);
GType gazette_recent_files_get_type (void) G_GNUC_CONST;
GazetteRSS* gazette_rss_new (void);
GazetteRSS* gazette_rss_construct (GType object_type);
GType gazette_rss_get_type (void) G_GNUC_CONST;
static void _vala_PangoFontDescription_free (PangoFontDescription* self);
static void _____lambda9_ (Block1Data* _data1_, GazetteService* s);
static void ______lambda9__gazette_service_activated (GazetteService* _sender, GazetteService* container, gpointer self);
static void _vala_PangoAttrList_free (PangoAttrList* self);
static void gazette_settings_finalize (GObject* obj);
gint _vala_main (gchar** args, int args_length1);


static void _g_object_unref0_ (gpointer var) {
	(var == NULL) ? NULL : (var = (g_object_unref (var), NULL));
}


static void _g_list_free__g_object_unref0_ (GList* self) {
	g_list_foreach (self, (GFunc) _g_object_unref0_, NULL);
	g_list_free (self);
}


static Block1Data* block1_data_ref (Block1Data* _data1_) {
	g_atomic_int_inc (&_data1_->_ref_count_);
	return _data1_;
}


static void block1_data_unref (void * _userdata_) {
	Block1Data* _data1_;
	_data1_ = (Block1Data*) _userdata_;
	if (g_atomic_int_dec_and_test (&_data1_->_ref_count_)) {
		GazetteSettings * self;
		self = _data1_->self;
		_g_object_unref0 (_data1_->cur_image);
		_g_object_unref0 (_data1_->cur_label);
		_g_object_unref0 (_data1_->view);
		_g_object_unref0 (self);
		g_slice_free (Block1Data, _data1_);
	}
}


static void _vala_PangoFontDescription_free (PangoFontDescription* self) {
	g_boxed_free (pango_font_description_get_type (), self);
}


static gpointer _g_object_ref0 (gpointer self) {
	return self ? g_object_ref (self) : NULL;
}


static void _____lambda9_ (Block1Data* _data1_, GazetteService* s) {
	GazetteSettings * self;
	GazetteService* _tmp0_;
	GazetteService* _tmp7_;
	GazetteService* _tmp8_;
	GazetteService* _tmp9_;
	GtkEventBox* _tmp10_;
	GtkStyleContext* _tmp11_ = NULL;
	GazetteService* _tmp12_;
	GtkEventBox* _tmp13_;
	GtkStyleContext* _tmp14_ = NULL;
	GazetteService* _tmp15_;
	GtkEventBox* _tmp16_;
	GtkStyleContext* _tmp17_ = NULL;
	GtkBox* _tmp18_;
	GazetteService* _tmp19_;
	GtkGrid* _tmp20_;
	GtkBox* _tmp21_;
	GtkLabel* _tmp22_;
	GazetteService* _tmp23_;
	GtkLabel* _tmp24_;
	const gchar* _tmp25_;
	const gchar* _tmp26_;
	GtkImage* _tmp27_;
	GazetteService* _tmp28_;
	GtkImage* _tmp29_;
	gchar* _tmp30_ = NULL;
	gchar* _tmp31_;
	gchar* _tmp32_;
	self = _data1_->self;
	g_return_if_fail (s != NULL);
	_tmp0_ = self->priv->current;
	if (_tmp0_ != NULL) {
		GazetteService* _tmp1_;
		GtkEventBox* _tmp2_;
		GtkStyleContext* _tmp3_ = NULL;
		GtkBox* _tmp4_;
		GazetteService* _tmp5_;
		GtkGrid* _tmp6_;
		_tmp1_ = self->priv->current;
		_tmp2_ = _tmp1_->item;
		_tmp3_ = gtk_widget_get_style_context ((GtkWidget*) _tmp2_);
		gtk_style_context_remove_class (_tmp3_, GTK_STYLE_CLASS_BUTTON);
		_tmp4_ = _data1_->view;
		_tmp5_ = self->priv->current;
		_tmp6_ = _tmp5_->container;
		gtk_container_remove ((GtkContainer*) _tmp4_, (GtkWidget*) _tmp6_);
	}
	_tmp7_ = s;
	_tmp8_ = _g_object_ref0 (_tmp7_);
	_g_object_unref0 (self->priv->current);
	self->priv->current = _tmp8_;
	_tmp9_ = s;
	_tmp10_ = _tmp9_->item;
	_tmp11_ = gtk_widget_get_style_context ((GtkWidget*) _tmp10_);
	gtk_style_context_add_class (_tmp11_, GTK_STYLE_CLASS_BUTTON);
	_tmp12_ = s;
	_tmp13_ = _tmp12_->item;
	_tmp14_ = gtk_widget_get_style_context ((GtkWidget*) _tmp13_);
	gtk_style_context_set_state (_tmp14_, GTK_STATE_FLAG_ACTIVE);
	_tmp15_ = s;
	_tmp16_ = _tmp15_->item;
	_tmp17_ = gtk_widget_get_style_context ((GtkWidget*) _tmp16_);
	gtk_style_context_invalidate (_tmp17_);
	_tmp18_ = _data1_->view;
	_tmp19_ = s;
	_tmp20_ = _tmp19_->container;
	gtk_container_add ((GtkContainer*) _tmp18_, (GtkWidget*) _tmp20_);
	_tmp21_ = _data1_->view;
	gtk_widget_show_all ((GtkWidget*) _tmp21_);
	_tmp22_ = _data1_->cur_label;
	_tmp23_ = s;
	_tmp24_ = _tmp23_->name;
	_tmp25_ = gtk_label_get_label (_tmp24_);
	_tmp26_ = _tmp25_;
	gtk_label_set_label (_tmp22_, _tmp26_);
	_tmp27_ = _data1_->cur_image;
	_tmp28_ = s;
	_tmp29_ = _tmp28_->icon;
	g_object_get (_tmp29_, "icon-name", &_tmp30_, NULL);
	_tmp31_ = _tmp30_;
	_tmp32_ = _tmp31_;
	g_object_set (_tmp27_, "icon-name", _tmp32_, NULL);
	_g_free0 (_tmp32_);
}


static void ______lambda9__gazette_service_activated (GazetteService* _sender, GazetteService* container, gpointer self) {
	_____lambda9_ (self, container);
}


static void _vala_PangoAttrList_free (PangoAttrList* self) {
	g_boxed_free (pango_attr_list_get_type (), self);
}


GazetteSettings* gazette_settings_construct (GType object_type) {
	GazetteSettings * self = NULL;
	Block1Data* _data1_;
	GazetteWeather* _tmp0_;
	GazetteRecentFiles* _tmp1_;
	GazetteRSS* _tmp2_;
	GtkBox* _tmp3_;
	GtkBox* box;
	GtkBox* _tmp4_;
	GtkBox* list;
	GtkBox* _tmp5_;
	GtkScrolledWindow* _tmp6_;
	GtkScrolledWindow* scrl;
	GtkScrolledWindow* _tmp7_;
	GtkBox* _tmp8_;
	GtkScrolledWindow* _tmp9_;
	GtkBox* _tmp10_;
	GtkBox* _tmp11_;
	GtkScrolledWindow* _tmp12_;
	GtkBox* _tmp13_;
	GtkBox* _tmp14_;
	GtkBox* _tmp15_;
	GtkBox* cur_box;
	const gchar* _tmp16_ = NULL;
	GtkLabel* _tmp17_;
	GtkImage* _tmp18_;
	GtkImage* _tmp19_;
	PangoAttrList* _tmp20_;
	PangoAttrList* attrs;
	PangoAttrList* _tmp21_;
	PangoFontDescription* _tmp22_ = NULL;
	PangoFontDescription* _tmp23_;
	PangoAttrFontDesc* _tmp24_;
	GtkLabel* _tmp25_;
	PangoAttrList* _tmp26_;
	GtkLabel* _tmp27_;
	GtkBox* _tmp28_;
	GtkImage* _tmp29_;
	GtkBox* _tmp30_;
	GtkLabel* _tmp31_;
	GtkBox* _tmp32_;
	GtkBox* _tmp33_;
	GtkBox* _tmp34_;
	GtkBox* _tmp49_;
	_data1_ = g_slice_new0 (Block1Data);
	_data1_->_ref_count_ = 1;
	self = (GazetteSettings*) pantheon_switchboard_plug_construct (object_type);
	_data1_->self = g_object_ref (self);
	__g_list_free__g_object_unref0_0 (self->priv->services);
	self->priv->services = NULL;
	_tmp0_ = gazette_weather_new ();
	self->priv->services = g_list_append (self->priv->services, (GazetteService*) _tmp0_);
	_tmp1_ = gazette_recent_files_new ();
	self->priv->services = g_list_append (self->priv->services, (GazetteService*) _tmp1_);
	_tmp2_ = gazette_rss_new ();
	self->priv->services = g_list_append (self->priv->services, (GazetteService*) _tmp2_);
	_tmp3_ = (GtkBox*) gtk_box_new (GTK_ORIENTATION_HORIZONTAL, 0);
	g_object_ref_sink (_tmp3_);
	box = _tmp3_;
	_tmp4_ = (GtkBox*) gtk_box_new (GTK_ORIENTATION_VERTICAL, 0);
	g_object_ref_sink (_tmp4_);
	list = _tmp4_;
	_tmp5_ = (GtkBox*) gtk_box_new (GTK_ORIENTATION_VERTICAL, 0);
	g_object_ref_sink (_tmp5_);
	_data1_->view = _tmp5_;
	_tmp6_ = (GtkScrolledWindow*) gtk_scrolled_window_new (NULL, NULL);
	g_object_ref_sink (_tmp6_);
	scrl = _tmp6_;
	_tmp7_ = scrl;
	_tmp8_ = list;
	gtk_scrolled_window_add_with_viewport (_tmp7_, (GtkWidget*) _tmp8_);
	_tmp9_ = scrl;
	g_object_set ((GtkWidget*) _tmp9_, "width-request", 300, NULL);
	_tmp10_ = list;
	g_object_set ((GtkWidget*) _tmp10_, "margin", 12, NULL);
	_tmp11_ = box;
	_tmp12_ = scrl;
	gtk_box_pack_start (_tmp11_, (GtkWidget*) _tmp12_, FALSE, TRUE, (guint) 0);
	_tmp13_ = box;
	_tmp14_ = _data1_->view;
	gtk_box_pack_start (_tmp13_, (GtkWidget*) _tmp14_, TRUE, TRUE, (guint) 0);
	_tmp15_ = (GtkBox*) gtk_box_new (GTK_ORIENTATION_HORIZONTAL, 20);
	g_object_ref_sink (_tmp15_);
	cur_box = _tmp15_;
	_tmp16_ = _ ("Setup your\nnews services");
	_tmp17_ = (GtkLabel*) gtk_label_new (_tmp16_);
	g_object_ref_sink (_tmp17_);
	_data1_->cur_label = _tmp17_;
	_tmp18_ = (GtkImage*) gtk_image_new_from_icon_name ("gazette", GTK_ICON_SIZE_DIALOG);
	g_object_ref_sink (_tmp18_);
	_data1_->cur_image = _tmp18_;
	_tmp19_ = _data1_->cur_image;
	gtk_image_set_pixel_size (_tmp19_, 64);
	_tmp20_ = pango_attr_list_new ();
	attrs = _tmp20_;
	_tmp21_ = attrs;
	_tmp22_ = pango_font_description_from_string ("bold 25");
	_tmp23_ = _tmp22_;
	_tmp24_ = (PangoAttrFontDesc*) pango_attr_font_desc_new (_tmp23_);
	pango_attr_list_insert (_tmp21_, (PangoAttribute*) _tmp24_);
	__vala_PangoFontDescription_free0 (_tmp23_);
	_tmp25_ = _data1_->cur_label;
	_tmp26_ = attrs;
	gtk_label_set_attributes (_tmp25_, _tmp26_);
	_tmp27_ = _data1_->cur_label;
	gtk_widget_set_halign ((GtkWidget*) _tmp27_, GTK_ALIGN_START);
	_tmp28_ = cur_box;
	_tmp29_ = _data1_->cur_image;
	gtk_box_pack_start (_tmp28_, (GtkWidget*) _tmp29_, FALSE, TRUE, (guint) 0);
	_tmp30_ = cur_box;
	_tmp31_ = _data1_->cur_label;
	gtk_box_pack_start (_tmp30_, (GtkWidget*) _tmp31_, TRUE, TRUE, (guint) 0);
	_tmp32_ = _data1_->view;
	_tmp33_ = cur_box;
	gtk_box_pack_start (_tmp32_, (GtkWidget*) _tmp33_, FALSE, TRUE, (guint) 0);
	_tmp34_ = _data1_->view;
	g_object_set ((GtkWidget*) _tmp34_, "margin", 30, NULL);
	{
		gint i;
		i = 0;
		{
			gboolean _tmp35_;
			_tmp35_ = TRUE;
			while (TRUE) {
				gboolean _tmp36_;
				gint _tmp38_;
				GList* _tmp39_;
				guint _tmp40_ = 0U;
				GList* _tmp41_;
				gint _tmp42_;
				gconstpointer _tmp43_ = NULL;
				GtkBox* _tmp44_;
				GList* _tmp45_;
				gint _tmp46_;
				gconstpointer _tmp47_ = NULL;
				GtkEventBox* _tmp48_;
				_tmp36_ = _tmp35_;
				if (!_tmp36_) {
					gint _tmp37_;
					_tmp37_ = i;
					i = _tmp37_ + 1;
				}
				_tmp35_ = FALSE;
				_tmp38_ = i;
				_tmp39_ = self->priv->services;
				_tmp40_ = g_list_length (_tmp39_);
				if (!(((guint) _tmp38_) < _tmp40_)) {
					break;
				}
				_tmp41_ = self->priv->services;
				_tmp42_ = i;
				_tmp43_ = g_list_nth_data (_tmp41_, (guint) _tmp42_);
				g_signal_connect_data ((GazetteService*) _tmp43_, "activated", (GCallback) ______lambda9__gazette_service_activated, block1_data_ref (_data1_), (GClosureNotify) block1_data_unref, 0);
				_tmp44_ = list;
				_tmp45_ = self->priv->services;
				_tmp46_ = i;
				_tmp47_ = g_list_nth_data (_tmp45_, (guint) _tmp46_);
				_tmp48_ = ((GazetteService*) _tmp47_)->item;
				gtk_box_pack_start (_tmp44_, (GtkWidget*) _tmp48_, FALSE, TRUE, (guint) 0);
			}
		}
	}
	_tmp49_ = box;
	gtk_container_add ((GtkContainer*) self, (GtkWidget*) _tmp49_);
	__vala_PangoAttrList_free0 (attrs);
	_g_object_unref0 (cur_box);
	_g_object_unref0 (scrl);
	_g_object_unref0 (list);
	_g_object_unref0 (box);
	block1_data_unref (_data1_);
	_data1_ = NULL;
	return self;
}


GazetteSettings* gazette_settings_new (void) {
	return gazette_settings_construct (TYPE_GAZETTE_SETTINGS);
}


static void gazette_settings_class_init (GazetteSettingsClass * klass) {
	gazette_settings_parent_class = g_type_class_peek_parent (klass);
	g_type_class_add_private (klass, sizeof (GazetteSettingsPrivate));
	G_OBJECT_CLASS (klass)->finalize = gazette_settings_finalize;
}


static void gazette_settings_instance_init (GazetteSettings * self) {
	self->priv = GAZETTE_SETTINGS_GET_PRIVATE (self);
}


static void gazette_settings_finalize (GObject* obj) {
	GazetteSettings * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, TYPE_GAZETTE_SETTINGS, GazetteSettings);
	__g_list_free__g_object_unref0_0 (self->priv->services);
	_g_object_unref0 (self->priv->current);
	G_OBJECT_CLASS (gazette_settings_parent_class)->finalize (obj);
}


GType gazette_settings_get_type (void) {
	static volatile gsize gazette_settings_type_id__volatile = 0;
	if (g_once_init_enter (&gazette_settings_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (GazetteSettingsClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) gazette_settings_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (GazetteSettings), 0, (GInstanceInitFunc) gazette_settings_instance_init, NULL };
		GType gazette_settings_type_id;
		gazette_settings_type_id = g_type_register_static (PANTHEON_SWITCHBOARD_TYPE_PLUG, "GazetteSettings", &g_define_type_info, 0);
		g_once_init_leave (&gazette_settings_type_id__volatile, gazette_settings_type_id);
	}
	return gazette_settings_type_id__volatile;
}


gint _vala_main (gchar** args, int args_length1) {
	gint result = 0;
	GazetteSettings* _tmp0_;
	GazetteSettings* SwitchBoard_Plug;
	const gchar* _tmp1_ = NULL;
	gtk_init (&args_length1, &args);
	_tmp0_ = gazette_settings_new ();
	g_object_ref_sink (_tmp0_);
	SwitchBoard_Plug = _tmp0_;
	_tmp1_ = _ ("Column News");
	pantheon_switchboard_plug_register ((PantheonSwitchboardPlug*) SwitchBoard_Plug, _tmp1_);
	gtk_widget_show_all ((GtkWidget*) SwitchBoard_Plug);
	gtk_main ();
	result = 0;
	_g_object_unref0 (SwitchBoard_Plug);
	return result;
}


int main (int argc, char ** argv) {
	g_thread_init (NULL);
	g_type_init ();
	return _vala_main (argv, argc);
}



