/* RecentFiles.c generated by valac 0.20.1, the Vala compiler
 * generated from RecentFiles.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <gio/gio.h>
#include <gtk/gtk.h>
#include <glib/gi18n-lib.h>
#include <stdlib.h>
#include <string.h>


#define GAZETTE_TYPE_SERVICE (gazette_service_get_type ())
#define GAZETTE_SERVICE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), GAZETTE_TYPE_SERVICE, GazetteService))
#define GAZETTE_SERVICE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), GAZETTE_TYPE_SERVICE, GazetteServiceClass))
#define GAZETTE_IS_SERVICE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), GAZETTE_TYPE_SERVICE))
#define GAZETTE_IS_SERVICE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), GAZETTE_TYPE_SERVICE))
#define GAZETTE_SERVICE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), GAZETTE_TYPE_SERVICE, GazetteServiceClass))

typedef struct _GazetteService GazetteService;
typedef struct _GazetteServiceClass GazetteServiceClass;
typedef struct _GazetteServicePrivate GazetteServicePrivate;

#define GAZETTE_TYPE_RECENT_FILES (gazette_recent_files_get_type ())
#define GAZETTE_RECENT_FILES(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), GAZETTE_TYPE_RECENT_FILES, GazetteRecentFiles))
#define GAZETTE_RECENT_FILES_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), GAZETTE_TYPE_RECENT_FILES, GazetteRecentFilesClass))
#define GAZETTE_IS_RECENT_FILES(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), GAZETTE_TYPE_RECENT_FILES))
#define GAZETTE_IS_RECENT_FILES_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), GAZETTE_TYPE_RECENT_FILES))
#define GAZETTE_RECENT_FILES_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), GAZETTE_TYPE_RECENT_FILES, GazetteRecentFilesClass))

typedef struct _GazetteRecentFiles GazetteRecentFiles;
typedef struct _GazetteRecentFilesClass GazetteRecentFilesClass;
typedef struct _GazetteRecentFilesPrivate GazetteRecentFilesPrivate;
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))

struct _GazetteService {
	GObject parent_instance;
	GazetteServicePrivate * priv;
	GtkGrid* container;
	GtkEventBox* item;
	GtkImage* icon;
	GtkSwitch* toggle;
	GtkLabel* name;
};

struct _GazetteServiceClass {
	GObjectClass parent_class;
	void (*run) (GazetteService* self, GFile* file);
};

struct _GazetteRecentFiles {
	GazetteService parent_instance;
	GazetteRecentFilesPrivate * priv;
};

struct _GazetteRecentFilesClass {
	GazetteServiceClass parent_class;
};


static gpointer gazette_recent_files_parent_class = NULL;

GType gazette_service_get_type (void) G_GNUC_CONST;
GType gazette_recent_files_get_type (void) G_GNUC_CONST;
enum  {
	GAZETTE_RECENT_FILES_DUMMY_PROPERTY
};
GazetteRecentFiles* gazette_recent_files_new (void);
GazetteRecentFiles* gazette_recent_files_construct (GType object_type);
GazetteService* gazette_service_new (const gchar* name, const gchar* icon);
GazetteService* gazette_service_construct (GType object_type, const gchar* name, const gchar* icon);
static void gazette_recent_files_real_run (GazetteService* base, GFile* file);


GazetteRecentFiles* gazette_recent_files_construct (GType object_type) {
	GazetteRecentFiles * self = NULL;
	const gchar* _tmp0_ = NULL;
	GtkGrid* _tmp1_;
	const gchar* _tmp2_ = NULL;
	GtkLabel* _tmp3_;
	GtkLabel* _tmp4_;
	_tmp0_ = _ ("Files");
	self = (GazetteRecentFiles*) gazette_service_construct (object_type, _tmp0_, "x-office-document");
	_tmp1_ = ((GazetteService*) self)->container;
	_tmp2_ = _ ("No settings yet.");
	_tmp3_ = (GtkLabel*) gtk_label_new (_tmp2_);
	g_object_ref_sink (_tmp3_);
	_tmp4_ = _tmp3_;
	gtk_grid_attach (_tmp1_, (GtkWidget*) _tmp4_, 0, 0, 1, 1);
	_g_object_unref0 (_tmp4_);
	return self;
}


GazetteRecentFiles* gazette_recent_files_new (void) {
	return gazette_recent_files_construct (GAZETTE_TYPE_RECENT_FILES);
}


static void gazette_recent_files_real_run (GazetteService* base, GFile* file) {
	GazetteRecentFiles * self;
	self = (GazetteRecentFiles*) base;
	g_return_if_fail (file != NULL);
}


static void gazette_recent_files_class_init (GazetteRecentFilesClass * klass) {
	gazette_recent_files_parent_class = g_type_class_peek_parent (klass);
	GAZETTE_SERVICE_CLASS (klass)->run = gazette_recent_files_real_run;
}


static void gazette_recent_files_instance_init (GazetteRecentFiles * self) {
}


GType gazette_recent_files_get_type (void) {
	static volatile gsize gazette_recent_files_type_id__volatile = 0;
	if (g_once_init_enter (&gazette_recent_files_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (GazetteRecentFilesClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) gazette_recent_files_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (GazetteRecentFiles), 0, (GInstanceInitFunc) gazette_recent_files_instance_init, NULL };
		GType gazette_recent_files_type_id;
		gazette_recent_files_type_id = g_type_register_static (GAZETTE_TYPE_SERVICE, "GazetteRecentFiles", &g_define_type_info, 0);
		g_once_init_leave (&gazette_recent_files_type_id__volatile, gazette_recent_files_type_id);
	}
	return gazette_recent_files_type_id__volatile;
}



