/* Service.c generated by valac 0.20.1, the Vala compiler
 * generated from Service.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <gio/gio.h>
#include <gtk/gtk.h>
#include <stdlib.h>
#include <string.h>
#include <gdk/gdk.h>


#define GAZETTE_TYPE_SERVICE (gazette_service_get_type ())
#define GAZETTE_SERVICE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), GAZETTE_TYPE_SERVICE, GazetteService))
#define GAZETTE_SERVICE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), GAZETTE_TYPE_SERVICE, GazetteServiceClass))
#define GAZETTE_IS_SERVICE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), GAZETTE_TYPE_SERVICE))
#define GAZETTE_IS_SERVICE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), GAZETTE_TYPE_SERVICE))
#define GAZETTE_SERVICE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), GAZETTE_TYPE_SERVICE, GazetteServiceClass))

typedef struct _GazetteService GazetteService;
typedef struct _GazetteServiceClass GazetteServiceClass;
typedef struct _GazetteServicePrivate GazetteServicePrivate;
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))

struct _GazetteService {
	GObject parent_instance;
	GazetteServicePrivate * priv;
	GtkGrid* container;
	GtkEventBox* item;
	GtkImage* icon;
	GtkSwitch* toggle;
	GtkLabel* name;
};

struct _GazetteServiceClass {
	GObjectClass parent_class;
	void (*run) (GazetteService* self, GFile* file);
};


static gpointer gazette_service_parent_class = NULL;

GType gazette_service_get_type (void) G_GNUC_CONST;
enum  {
	GAZETTE_SERVICE_DUMMY_PROPERTY
};
GazetteService* gazette_service_new (const gchar* name, const gchar* icon);
GazetteService* gazette_service_construct (GType object_type, const gchar* name, const gchar* icon);
static gboolean __lambda2_ (GazetteService* self);
static gboolean ___lambda2__gtk_widget_button_press_event (GtkWidget* _sender, GdkEventButton* event, gpointer self);
void gazette_service_run (GazetteService* self, GFile* file);
static void gazette_service_real_run (GazetteService* self, GFile* file);
static void gazette_service_finalize (GObject* obj);


static gboolean __lambda2_ (GazetteService* self) {
	gboolean result = FALSE;
	g_signal_emit_by_name (self, "activated", self);
	result = FALSE;
	return result;
}


static gboolean ___lambda2__gtk_widget_button_press_event (GtkWidget* _sender, GdkEventButton* event, gpointer self) {
	gboolean result;
	result = __lambda2_ (self);
	return result;
}


GazetteService* gazette_service_construct (GType object_type, const gchar* name, const gchar* icon) {
	GazetteService * self = NULL;
	const gchar* _tmp0_;
	GtkLabel* _tmp1_;
	const gchar* _tmp2_;
	GtkImage* _tmp3_;
	GtkEventBox* _tmp4_;
	GtkBox* _tmp5_;
	GtkBox* item_c;
	GtkSwitch* _tmp6_;
	GtkGrid* _tmp7_;
	GtkGrid* _tmp8_;
	GtkGrid* _tmp9_;
	GtkGrid* _tmp10_;
	GtkGrid* _tmp11_;
	GtkImage* _tmp12_;
	GtkLabel* _tmp13_;
	GtkSwitch* _tmp14_;
	GtkEventBox* _tmp15_;
	GtkEventBox* _tmp16_;
	GtkEventBox* _tmp17_;
	GtkEventBox* _tmp18_;
	GtkSwitch* _tmp19_;
	GtkSwitch* _tmp20_;
	GtkEventBox* _tmp21_;
	g_return_val_if_fail (name != NULL, NULL);
	g_return_val_if_fail (icon != NULL, NULL);
	self = (GazetteService*) g_object_new (object_type, NULL);
	_tmp0_ = name;
	_tmp1_ = (GtkLabel*) gtk_label_new (_tmp0_);
	g_object_ref_sink (_tmp1_);
	_g_object_unref0 (self->name);
	self->name = _tmp1_;
	_tmp2_ = icon;
	_tmp3_ = (GtkImage*) gtk_image_new_from_icon_name (_tmp2_, GTK_ICON_SIZE_DIALOG);
	g_object_ref_sink (_tmp3_);
	_g_object_unref0 (self->icon);
	self->icon = _tmp3_;
	_tmp4_ = (GtkEventBox*) gtk_event_box_new ();
	g_object_ref_sink (_tmp4_);
	_g_object_unref0 (self->item);
	self->item = _tmp4_;
	_tmp5_ = (GtkBox*) gtk_box_new (GTK_ORIENTATION_HORIZONTAL, 5);
	g_object_ref_sink (_tmp5_);
	item_c = _tmp5_;
	_tmp6_ = (GtkSwitch*) gtk_switch_new ();
	g_object_ref_sink (_tmp6_);
	_g_object_unref0 (self->toggle);
	self->toggle = _tmp6_;
	_tmp7_ = (GtkGrid*) gtk_grid_new ();
	g_object_ref_sink (_tmp7_);
	_g_object_unref0 (self->container);
	self->container = _tmp7_;
	_tmp8_ = self->container;
	g_object_set ((GtkWidget*) _tmp8_, "margin", 12, NULL);
	_tmp9_ = self->container;
	gtk_grid_set_row_spacing (_tmp9_, 12);
	_tmp10_ = self->container;
	gtk_grid_set_column_spacing (_tmp10_, 12);
	_tmp11_ = self->container;
	gtk_grid_set_column_homogeneous (_tmp11_, TRUE);
	_tmp12_ = self->icon;
	gtk_box_pack_start (item_c, (GtkWidget*) _tmp12_, FALSE, TRUE, (guint) 0);
	_tmp13_ = self->name;
	gtk_box_pack_start (item_c, (GtkWidget*) _tmp13_, TRUE, TRUE, (guint) 0);
	_tmp14_ = self->toggle;
	gtk_box_pack_start (item_c, (GtkWidget*) _tmp14_, FALSE, TRUE, (guint) 0);
	_tmp15_ = self->item;
	gtk_container_add ((GtkContainer*) _tmp15_, (GtkWidget*) item_c);
	_tmp16_ = self->item;
	_tmp17_ = self->item;
	gtk_widget_set_margin_bottom ((GtkWidget*) _tmp17_, 5);
	gtk_widget_set_margin_top ((GtkWidget*) _tmp16_, 5);
	_tmp18_ = self->item;
	gtk_event_box_set_visible_window (_tmp18_, FALSE);
	_tmp19_ = self->toggle;
	gtk_widget_set_valign ((GtkWidget*) _tmp19_, GTK_ALIGN_CENTER);
	_tmp20_ = self->toggle;
	gtk_switch_set_active (_tmp20_, TRUE);
	_tmp21_ = self->item;
	g_signal_connect_object ((GtkWidget*) _tmp21_, "button-press-event", (GCallback) ___lambda2__gtk_widget_button_press_event, self, 0);
	_g_object_unref0 (item_c);
	return self;
}


GazetteService* gazette_service_new (const gchar* name, const gchar* icon) {
	return gazette_service_construct (GAZETTE_TYPE_SERVICE, name, icon);
}


static void gazette_service_real_run (GazetteService* self, GFile* file) {
	g_return_if_fail (file != NULL);
}


void gazette_service_run (GazetteService* self, GFile* file) {
	g_return_if_fail (self != NULL);
	GAZETTE_SERVICE_GET_CLASS (self)->run (self, file);
}


static void gazette_service_class_init (GazetteServiceClass * klass) {
	gazette_service_parent_class = g_type_class_peek_parent (klass);
	GAZETTE_SERVICE_CLASS (klass)->run = gazette_service_real_run;
	G_OBJECT_CLASS (klass)->finalize = gazette_service_finalize;
	g_signal_new ("activated", GAZETTE_TYPE_SERVICE, G_SIGNAL_RUN_LAST, 0, NULL, NULL, g_cclosure_marshal_VOID__OBJECT, G_TYPE_NONE, 1, GAZETTE_TYPE_SERVICE);
}


static void gazette_service_instance_init (GazetteService * self) {
}


static void gazette_service_finalize (GObject* obj) {
	GazetteService * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, GAZETTE_TYPE_SERVICE, GazetteService);
	_g_object_unref0 (self->container);
	_g_object_unref0 (self->item);
	_g_object_unref0 (self->icon);
	_g_object_unref0 (self->toggle);
	_g_object_unref0 (self->name);
	G_OBJECT_CLASS (gazette_service_parent_class)->finalize (obj);
}


GType gazette_service_get_type (void) {
	static volatile gsize gazette_service_type_id__volatile = 0;
	if (g_once_init_enter (&gazette_service_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (GazetteServiceClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) gazette_service_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (GazetteService), 0, (GInstanceInitFunc) gazette_service_instance_init, NULL };
		GType gazette_service_type_id;
		gazette_service_type_id = g_type_register_static (G_TYPE_OBJECT, "GazetteService", &g_define_type_info, 0);
		g_once_init_leave (&gazette_service_type_id__volatile, gazette_service_type_id);
	}
	return gazette_service_type_id__volatile;
}



