/* Weather.c generated by valac 0.20.1, the Vala compiler
 * generated from Weather.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <gio/gio.h>
#include <gtk/gtk.h>
#include <stdlib.h>
#include <string.h>
#include <glib/gi18n-lib.h>
#include <stdio.h>
#include <float.h>
#include <math.h>


#define GAZETTE_TYPE_SERVICE (gazette_service_get_type ())
#define GAZETTE_SERVICE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), GAZETTE_TYPE_SERVICE, GazetteService))
#define GAZETTE_SERVICE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), GAZETTE_TYPE_SERVICE, GazetteServiceClass))
#define GAZETTE_IS_SERVICE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), GAZETTE_TYPE_SERVICE))
#define GAZETTE_IS_SERVICE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), GAZETTE_TYPE_SERVICE))
#define GAZETTE_SERVICE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), GAZETTE_TYPE_SERVICE, GazetteServiceClass))

typedef struct _GazetteService GazetteService;
typedef struct _GazetteServiceClass GazetteServiceClass;
typedef struct _GazetteServicePrivate GazetteServicePrivate;

#define GAZETTE_TYPE_WEATHER (gazette_weather_get_type ())
#define GAZETTE_WEATHER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), GAZETTE_TYPE_WEATHER, GazetteWeather))
#define GAZETTE_WEATHER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), GAZETTE_TYPE_WEATHER, GazetteWeatherClass))
#define GAZETTE_IS_WEATHER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), GAZETTE_TYPE_WEATHER))
#define GAZETTE_IS_WEATHER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), GAZETTE_TYPE_WEATHER))
#define GAZETTE_WEATHER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), GAZETTE_TYPE_WEATHER, GazetteWeatherClass))

typedef struct _GazetteWeather GazetteWeather;
typedef struct _GazetteWeatherClass GazetteWeatherClass;
typedef struct _GazetteWeatherPrivate GazetteWeatherPrivate;
#define _g_free0(var) (var = (g_free (var), NULL))
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
typedef struct _Block3Data Block3Data;
#define _g_error_free0(var) ((var == NULL) ? NULL : (var = (g_error_free (var), NULL)))

struct _GazetteService {
	GObject parent_instance;
	GazetteServicePrivate * priv;
	GtkGrid* container;
	GtkEventBox* item;
	GtkImage* icon;
	GtkSwitch* toggle;
	GtkLabel* name;
};

struct _GazetteServiceClass {
	GObjectClass parent_class;
	void (*run) (GazetteService* self, GFile* file);
};

struct _GazetteWeather {
	GazetteService parent_instance;
	GazetteWeatherPrivate * priv;
	gint weather_id;
	gchar* weather_unit;
};

struct _GazetteWeatherClass {
	GazetteServiceClass parent_class;
};

struct _GazetteWeatherPrivate {
	GSettings* settings;
};

struct _Block3Data {
	int _ref_count_;
	GazetteWeather * self;
	GtkSpinButton* weatherIdEntry;
	GtkComboBoxText* weatherUnitBox;
	gchar* new_unit;
};


static gpointer gazette_weather_parent_class = NULL;

GType gazette_service_get_type (void) G_GNUC_CONST;
GType gazette_weather_get_type (void) G_GNUC_CONST;
#define GAZETTE_WEATHER_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), GAZETTE_TYPE_WEATHER, GazetteWeatherPrivate))
enum  {
	GAZETTE_WEATHER_DUMMY_PROPERTY
};
GazetteWeather* gazette_weather_new (void);
GazetteWeather* gazette_weather_construct (GType object_type);
static Block3Data* block3_data_ref (Block3Data* _data3_);
static void block3_data_unref (void * _userdata_);
GazetteService* gazette_service_new (const gchar* name, const gchar* icon);
GazetteService* gazette_service_construct (GType object_type, const gchar* name, const gchar* icon);
static void __lambda3_ (Block3Data* _data3_);
static void ___lambda3__gtk_spin_button_value_changed (GtkSpinButton* _sender, gpointer self);
static void __lambda4_ (Block3Data* _data3_);
static void ___lambda4__gtk_combo_box_changed (GtkComboBox* _sender, gpointer self);
static void __lambda5_ (Block3Data* _data3_);
static void ___lambda5__gtk_button_clicked (GtkButton* _sender, gpointer self);
static void gazette_weather_real_run (GazetteService* base, GFile* file);
static void gazette_weather_finalize (GObject* obj);


static Block3Data* block3_data_ref (Block3Data* _data3_) {
	g_atomic_int_inc (&_data3_->_ref_count_);
	return _data3_;
}


static void block3_data_unref (void * _userdata_) {
	Block3Data* _data3_;
	_data3_ = (Block3Data*) _userdata_;
	if (g_atomic_int_dec_and_test (&_data3_->_ref_count_)) {
		GazetteWeather * self;
		self = _data3_->self;
		_g_free0 (_data3_->new_unit);
		_g_object_unref0 (_data3_->weatherUnitBox);
		_g_object_unref0 (_data3_->weatherIdEntry);
		_g_object_unref0 (self);
		g_slice_free (Block3Data, _data3_);
	}
}


static void __lambda3_ (Block3Data* _data3_) {
	GazetteWeather * self;
	GSettings* _tmp0_;
	GtkSpinButton* _tmp1_;
	gint _tmp2_ = 0;
	self = _data3_->self;
	_tmp0_ = self->priv->settings;
	_tmp1_ = _data3_->weatherIdEntry;
	_tmp2_ = gtk_spin_button_get_value_as_int (_tmp1_);
	g_settings_set_int (_tmp0_, "weather-id", _tmp2_);
}


static void ___lambda3__gtk_spin_button_value_changed (GtkSpinButton* _sender, gpointer self) {
	__lambda3_ (self);
}


static void __lambda4_ (Block3Data* _data3_) {
	GazetteWeather * self;
	GtkComboBoxText* _tmp0_;
	const gchar* _tmp1_ = NULL;
	GSettings* _tmp4_;
	const gchar* _tmp5_;
	self = _data3_->self;
	_tmp0_ = _data3_->weatherUnitBox;
	_tmp1_ = gtk_combo_box_text_get_active_text (_tmp0_);
	if (g_strcmp0 (_tmp1_, "Celsius") == 0) {
		gchar* _tmp2_;
		_tmp2_ = g_strdup ("Celsius");
		_g_free0 (_data3_->new_unit);
		_data3_->new_unit = _tmp2_;
	} else {
		gchar* _tmp3_;
		_tmp3_ = g_strdup ("Fahrenheit");
		_g_free0 (_data3_->new_unit);
		_data3_->new_unit = _tmp3_;
	}
	_tmp4_ = self->priv->settings;
	_tmp5_ = _data3_->new_unit;
	g_settings_set_string (_tmp4_, "weather-unit", _tmp5_);
}


static void ___lambda4__gtk_combo_box_changed (GtkComboBox* _sender, gpointer self) {
	__lambda4_ (self);
}


static void __lambda5_ (Block3Data* _data3_) {
	GazetteWeather * self;
	GSettings* _tmp0_;
	GSettings* _tmp1_;
	GSettings* _tmp2_;
	gint _tmp3_ = 0;
	GSettings* _tmp4_;
	gchar* _tmp5_ = NULL;
	GtkSpinButton* _tmp6_;
	gint _tmp7_;
	const gchar* _tmp8_;
	self = _data3_->self;
	_tmp0_ = self->priv->settings;
	g_settings_reset (_tmp0_, "weather-unit");
	_tmp1_ = self->priv->settings;
	g_settings_reset (_tmp1_, "weather-id");
	_tmp2_ = self->priv->settings;
	_tmp3_ = g_settings_get_int (_tmp2_, "weather-id");
	self->weather_id = _tmp3_;
	_tmp4_ = self->priv->settings;
	_tmp5_ = g_settings_get_string (_tmp4_, "weather-unit");
	_g_free0 (self->weather_unit);
	self->weather_unit = _tmp5_;
	_tmp6_ = _data3_->weatherIdEntry;
	_tmp7_ = self->weather_id;
	gtk_spin_button_set_value (_tmp6_, (gdouble) _tmp7_);
	_tmp8_ = self->weather_unit;
	if (g_strcmp0 (_tmp8_, "'Celsius'") == 0) {
		GtkComboBoxText* _tmp9_;
		_tmp9_ = _data3_->weatherUnitBox;
		gtk_combo_box_set_active ((GtkComboBox*) _tmp9_, 1);
	} else {
		GtkComboBoxText* _tmp10_;
		_tmp10_ = _data3_->weatherUnitBox;
		gtk_combo_box_set_active ((GtkComboBox*) _tmp10_, 0);
	}
}


static void ___lambda5__gtk_button_clicked (GtkButton* _sender, gpointer self) {
	__lambda5_ (self);
}


GazetteWeather* gazette_weather_construct (GType object_type) {
	GazetteWeather * self = NULL;
	Block3Data* _data3_;
	const gchar* _tmp0_ = NULL;
	GSettings* _tmp1_;
	const gchar* _tmp9_ = NULL;
	gchar* _tmp10_;
	gchar* _tmp11_;
	gchar* _tmp12_;
	gchar* _tmp13_;
	const gchar* _tmp14_ = NULL;
	gchar* _tmp15_;
	gchar* _tmp16_;
	gchar* _tmp17_;
	gchar* _tmp18_;
	GtkLabel* _tmp19_;
	GtkLabel* _tmp20_;
	GtkLabel* weatherIdLabel;
	GtkGrid* _tmp21_;
	GtkLabel* _tmp22_;
	GtkSpinButton* _tmp23_;
	GtkSpinButton* _tmp24_;
	gint _tmp25_;
	GtkSpinButton* _tmp26_;
	GtkGrid* _tmp27_;
	GtkSpinButton* _tmp28_;
	const gchar* _tmp29_ = NULL;
	gchar* _tmp30_;
	gchar* _tmp31_;
	gchar* _tmp32_;
	gchar* _tmp33_;
	GtkLabel* _tmp34_;
	GtkLabel* _tmp35_;
	GtkLabel* weatherIdHelp;
	GtkLabel* _tmp36_;
	GtkLabel* _tmp37_;
	GtkGrid* _tmp38_;
	GtkLabel* _tmp39_;
	GtkLabel* _tmp40_;
	GtkComboBoxText* _tmp41_;
	gchar* _tmp42_;
	GtkComboBoxText* _tmp43_;
	GtkComboBoxText* _tmp44_;
	const gchar* _tmp45_;
	GtkGrid* _tmp48_;
	GtkComboBoxText* _tmp49_;
	GtkComboBoxText* _tmp50_;
	const gchar* _tmp51_ = NULL;
	gchar* _tmp52_;
	gchar* _tmp53_;
	gchar* _tmp54_;
	gchar* _tmp55_;
	GtkLabel* _tmp56_;
	GtkLabel* _tmp57_;
	GtkLabel* weatherUnitLabel;
	GtkGrid* _tmp58_;
	const gchar* _tmp59_ = NULL;
	GtkButton* _tmp60_;
	GtkButton* resetButton;
	GtkGrid* _tmp61_;
	GError * _inner_error_ = NULL;
	_data3_ = g_slice_new0 (Block3Data);
	_data3_->_ref_count_ = 1;
	_tmp0_ = _ ("Weather Forecast");
	self = (GazetteWeather*) gazette_service_construct (object_type, _tmp0_, "preferences-desktop-online-accounts");
	_data3_->self = g_object_ref (self);
	_tmp1_ = g_settings_new ("org.pantheon.gazette.weather");
	_g_object_unref0 (self->priv->settings);
	self->priv->settings = _tmp1_;
	{
		GSettings* _tmp2_;
		gint _tmp3_ = 0;
		GSettings* _tmp4_;
		gchar* _tmp5_ = NULL;
		_tmp2_ = self->priv->settings;
		_tmp3_ = g_settings_get_int (_tmp2_, "weather-id");
		self->weather_id = _tmp3_;
		_tmp4_ = self->priv->settings;
		_tmp5_ = g_settings_get_string (_tmp4_, "weather-unit");
		_g_free0 (self->weather_unit);
		self->weather_unit = _tmp5_;
	}
	goto __finally1;
	__catch1_g_error:
	{
		GError* e = NULL;
		FILE* _tmp6_;
		GError* _tmp7_;
		const gchar* _tmp8_;
		e = _inner_error_;
		_inner_error_ = NULL;
		_tmp6_ = stderr;
		_tmp7_ = e;
		_tmp8_ = _tmp7_->message;
		fprintf (_tmp6_, "Unable to find settings: %s\n", _tmp8_);
		_g_error_free0 (e);
	}
	__finally1:
	if (_inner_error_ != NULL) {
		block3_data_unref (_data3_);
		_data3_ = NULL;
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return NULL;
	}
	_tmp9_ = _ ("Location ID");
	_tmp10_ = g_strconcat ("* ", _tmp9_, NULL);
	_tmp11_ = _tmp10_;
	_tmp12_ = g_strconcat (_tmp11_, " / ", NULL);
	_tmp13_ = _tmp12_;
	_tmp14_ = _ ("Unit");
	_tmp15_ = g_strconcat (_tmp13_, _tmp14_, NULL);
	_tmp16_ = _tmp15_;
	_tmp17_ = g_strconcat (_tmp16_, " :", NULL);
	_tmp18_ = _tmp17_;
	_tmp19_ = (GtkLabel*) gtk_label_new (_tmp18_);
	g_object_ref_sink (_tmp19_);
	_tmp20_ = _tmp19_;
	_g_free0 (_tmp18_);
	_g_free0 (_tmp16_);
	_g_free0 (_tmp13_);
	_g_free0 (_tmp11_);
	weatherIdLabel = _tmp20_;
	_tmp21_ = ((GazetteService*) self)->container;
	_tmp22_ = weatherIdLabel;
	gtk_grid_attach (_tmp21_, (GtkWidget*) _tmp22_, 0, 0, 1, 1);
	_tmp23_ = (GtkSpinButton*) gtk_spin_button_new_with_range ((gdouble) 10000, (gdouble) 99999999, (gdouble) 1);
	g_object_ref_sink (_tmp23_);
	_data3_->weatherIdEntry = _tmp23_;
	_tmp24_ = _data3_->weatherIdEntry;
	_tmp25_ = self->weather_id;
	gtk_spin_button_set_value (_tmp24_, (gdouble) _tmp25_);
	_tmp26_ = _data3_->weatherIdEntry;
	g_signal_connect_data (_tmp26_, "value-changed", (GCallback) ___lambda3__gtk_spin_button_value_changed, block3_data_ref (_data3_), (GClosureNotify) block3_data_unref, 0);
	_tmp27_ = ((GazetteService*) self)->container;
	_tmp28_ = _data3_->weatherIdEntry;
	gtk_grid_attach (_tmp27_, (GtkWidget*) _tmp28_, 1, 0, 1, 1);
	_tmp29_ = _ ("Example: If the URL is <i>http://weather.yahoo.com/united-kingdom/engl" \
"and/london-44418/</i> the city's ID is 44418.");
	_tmp30_ = g_strconcat ("<span font_desc=\"8.0\">*", _tmp29_, NULL);
	_tmp31_ = _tmp30_;
	_tmp32_ = g_strconcat (_tmp31_, "</span>", NULL);
	_tmp33_ = _tmp32_;
	_tmp34_ = (GtkLabel*) gtk_label_new (_tmp33_);
	g_object_ref_sink (_tmp34_);
	_tmp35_ = _tmp34_;
	_g_free0 (_tmp33_);
	_g_free0 (_tmp31_);
	weatherIdHelp = _tmp35_;
	_tmp36_ = weatherIdHelp;
	gtk_label_set_use_markup (_tmp36_, TRUE);
	_tmp37_ = weatherIdHelp;
	gtk_label_set_line_wrap (_tmp37_, TRUE);
	_tmp38_ = ((GazetteService*) self)->container;
	_tmp39_ = weatherIdHelp;
	gtk_grid_attach (_tmp38_, (GtkWidget*) _tmp39_, 1, 1, 2, 1);
	_tmp40_ = weatherIdHelp;
	gtk_misc_set_alignment ((GtkMisc*) _tmp40_, (gfloat) 0, (gfloat) 0);
	_tmp41_ = (GtkComboBoxText*) gtk_combo_box_text_new ();
	g_object_ref_sink (_tmp41_);
	_data3_->weatherUnitBox = _tmp41_;
	_tmp42_ = g_strdup ("");
	_data3_->new_unit = _tmp42_;
	_tmp43_ = _data3_->weatherUnitBox;
	gtk_combo_box_text_append_text (_tmp43_, "Celsius");
	_tmp44_ = _data3_->weatherUnitBox;
	gtk_combo_box_text_append_text (_tmp44_, "Fahrenheit");
	_tmp45_ = self->weather_unit;
	if (g_strcmp0 (_tmp45_, "'Celsius'") == 0) {
		GtkComboBoxText* _tmp46_;
		_tmp46_ = _data3_->weatherUnitBox;
		gtk_combo_box_set_active ((GtkComboBox*) _tmp46_, 1);
	} else {
		GtkComboBoxText* _tmp47_;
		_tmp47_ = _data3_->weatherUnitBox;
		gtk_combo_box_set_active ((GtkComboBox*) _tmp47_, 0);
	}
	_tmp48_ = ((GazetteService*) self)->container;
	_tmp49_ = _data3_->weatherUnitBox;
	gtk_grid_attach (_tmp48_, (GtkWidget*) _tmp49_, 2, 0, 1, 1);
	_tmp50_ = _data3_->weatherUnitBox;
	g_signal_connect_data ((GtkComboBox*) _tmp50_, "changed", (GCallback) ___lambda4__gtk_combo_box_changed, block3_data_ref (_data3_), (GClosureNotify) block3_data_unref, 0);
	_tmp51_ = _ ("Search Location ID on Yahoo!® Weather");
	_tmp52_ = g_strconcat ("<a href='http://weather.yahoo.com'>", _tmp51_, NULL);
	_tmp53_ = _tmp52_;
	_tmp54_ = g_strconcat (_tmp53_, "</a> :", NULL);
	_tmp55_ = _tmp54_;
	_tmp56_ = (GtkLabel*) gtk_label_new (_tmp55_);
	g_object_ref_sink (_tmp56_);
	_tmp57_ = _tmp56_;
	_g_free0 (_tmp55_);
	_g_free0 (_tmp53_);
	weatherUnitLabel = _tmp57_;
	_tmp58_ = ((GazetteService*) self)->container;
	gtk_grid_attach (_tmp58_, (GtkWidget*) weatherUnitLabel, 0, 1, 1, 1);
	gtk_misc_set_alignment ((GtkMisc*) weatherUnitLabel, (gfloat) 1, (gfloat) 0);
	gtk_label_set_use_markup (weatherUnitLabel, TRUE);
	gtk_label_set_line_wrap (weatherUnitLabel, TRUE);
	_tmp59_ = _ ("Reset");
	_tmp60_ = (GtkButton*) gtk_button_new_with_label (_tmp59_);
	g_object_ref_sink (_tmp60_);
	resetButton = _tmp60_;
	_tmp61_ = ((GazetteService*) self)->container;
	gtk_grid_attach (_tmp61_, (GtkWidget*) resetButton, 2, 2, 1, 1);
	g_signal_connect_data (resetButton, "clicked", (GCallback) ___lambda5__gtk_button_clicked, block3_data_ref (_data3_), (GClosureNotify) block3_data_unref, 0);
	_g_object_unref0 (resetButton);
	_g_object_unref0 (weatherUnitLabel);
	_g_object_unref0 (weatherIdHelp);
	_g_object_unref0 (weatherIdLabel);
	block3_data_unref (_data3_);
	_data3_ = NULL;
	return self;
}


GazetteWeather* gazette_weather_new (void) {
	return gazette_weather_construct (GAZETTE_TYPE_WEATHER);
}


static void gazette_weather_real_run (GazetteService* base, GFile* file) {
	GazetteWeather * self;
	self = (GazetteWeather*) base;
	g_return_if_fail (file != NULL);
}


static void gazette_weather_class_init (GazetteWeatherClass * klass) {
	gazette_weather_parent_class = g_type_class_peek_parent (klass);
	g_type_class_add_private (klass, sizeof (GazetteWeatherPrivate));
	GAZETTE_SERVICE_CLASS (klass)->run = gazette_weather_real_run;
	G_OBJECT_CLASS (klass)->finalize = gazette_weather_finalize;
}


static void gazette_weather_instance_init (GazetteWeather * self) {
	gchar* _tmp0_;
	self->priv = GAZETTE_WEATHER_GET_PRIVATE (self);
	_tmp0_ = g_strdup ("'Celsius'");
	self->weather_unit = _tmp0_;
}


static void gazette_weather_finalize (GObject* obj) {
	GazetteWeather * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, GAZETTE_TYPE_WEATHER, GazetteWeather);
	_g_free0 (self->weather_unit);
	_g_object_unref0 (self->priv->settings);
	G_OBJECT_CLASS (gazette_weather_parent_class)->finalize (obj);
}


GType gazette_weather_get_type (void) {
	static volatile gsize gazette_weather_type_id__volatile = 0;
	if (g_once_init_enter (&gazette_weather_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (GazetteWeatherClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) gazette_weather_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (GazetteWeather), 0, (GInstanceInitFunc) gazette_weather_instance_init, NULL };
		GType gazette_weather_type_id;
		gazette_weather_type_id = g_type_register_static (GAZETTE_TYPE_SERVICE, "GazetteWeather", &g_define_type_info, 0);
		g_once_init_leave (&gazette_weather_type_id__volatile, gazette_weather_type_id);
	}
	return gazette_weather_type_id__volatile;
}



