/* Config.c generated by valac 0.20.1, the Vala compiler
 * generated from Config.vala, do not modify */

/**/
/*  Copyright (C) 2011 Tom Beckmann*/
/**/
/*  This program is free software: you can redistribute it and/or modify*/
/*  it under the terms of the GNU General Public License as published by*/
/*  the Free Software Foundation, either version 3 of the License, or*/
/*  (at your option) any later version.*/
/**/
/*  This program is distributed in the hope that it will be useful,*/
/*  but WITHOUT ANY WARRANTY; without even the implied warranty of*/
/*  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the*/
/*  GNU General Public License for more details.*/
/**/
/*  You should have received a copy of the GNU General Public License*/
/*  along with this program.  If not, see <http://www.gnu.org/licenses/>.*/
/**/

#include <glib.h>
#include <glib-object.h>
#include <stdlib.h>
#include <string.h>




#define CONSTANTS_DATADIR "/usr/share"
#define CONSTANTS_PKGDATADIR "/usr/share/gazette"
#define CONSTANTS_GETTEXT_PACKAGE "gazette"
#define CONSTANTS_RELEASE_NAME "Simple and functional."
#define CONSTANTS_VERSION "0.1"
#define CONSTANTS_VERSION_INFO "Release"
#define CONSTANTS_PLUGINDIR ""
#define CONSTANTS_SCHEMA "org.pantheon.gazette"



