/* Gazette.c generated by valac 0.20.1, the Vala compiler
 * generated from Gazette.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <stdlib.h>
#include <string.h>
#include <granite.h>
#include <clutter/clutter.h>
#include <gtk/gtk.h>
#include <glib/gi18n-lib.h>
#include <float.h>
#include <math.h>
#include <gio/gio.h>
#include <clutter-gtk/clutter-gtk.h>


#define TYPE_GLOBAL_SETTINGS (global_settings_get_type ())
#define GLOBAL_SETTINGS(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_GLOBAL_SETTINGS, GlobalSettings))
#define GLOBAL_SETTINGS_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_GLOBAL_SETTINGS, GlobalSettingsClass))
#define IS_GLOBAL_SETTINGS(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_GLOBAL_SETTINGS))
#define IS_GLOBAL_SETTINGS_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_GLOBAL_SETTINGS))
#define GLOBAL_SETTINGS_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_GLOBAL_SETTINGS, GlobalSettingsClass))

typedef struct _GlobalSettings GlobalSettings;
typedef struct _GlobalSettingsClass GlobalSettingsClass;
typedef struct _GlobalSettingsPrivate GlobalSettingsPrivate;
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))

#define TYPE_GAZETTE (gazette_get_type ())
#define GAZETTE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_GAZETTE, Gazette))
#define GAZETTE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_GAZETTE, GazetteClass))
#define IS_GAZETTE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_GAZETTE))
#define IS_GAZETTE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_GAZETTE))
#define GAZETTE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_GAZETTE, GazetteClass))

typedef struct _Gazette Gazette;
typedef struct _GazetteClass GazetteClass;
typedef struct _GazettePrivate GazettePrivate;

#define TYPE_GAZETTE_WINDOW (gazette_window_get_type ())
#define GAZETTE_WINDOW(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_GAZETTE_WINDOW, GazetteWindow))
#define GAZETTE_WINDOW_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_GAZETTE_WINDOW, GazetteWindowClass))
#define IS_GAZETTE_WINDOW(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_GAZETTE_WINDOW))
#define IS_GAZETTE_WINDOW_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_GAZETTE_WINDOW))
#define GAZETTE_WINDOW_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_GAZETTE_WINDOW, GazetteWindowClass))

typedef struct _GazetteWindow GazetteWindow;
typedef struct _GazetteWindowClass GazetteWindowClass;

#define TYPE_SHADOWED_LABEL (shadowed_label_get_type ())
#define SHADOWED_LABEL(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_SHADOWED_LABEL, ShadowedLabel))
#define SHADOWED_LABEL_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_SHADOWED_LABEL, ShadowedLabelClass))
#define IS_SHADOWED_LABEL(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_SHADOWED_LABEL))
#define IS_SHADOWED_LABEL_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_SHADOWED_LABEL))
#define SHADOWED_LABEL_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_SHADOWED_LABEL, ShadowedLabelClass))

typedef struct _ShadowedLabel ShadowedLabel;
typedef struct _ShadowedLabelClass ShadowedLabelClass;
typedef struct _Block1Data Block1Data;
#define _g_free0(var) (var = (g_free (var), NULL))

#define TYPE_SERVICE (service_get_type ())
#define SERVICE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_SERVICE, Service))
#define SERVICE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_SERVICE, ServiceClass))
#define IS_SERVICE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_SERVICE))
#define IS_SERVICE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_SERVICE))
#define SERVICE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_SERVICE, ServiceClass))

typedef struct _Service Service;
typedef struct _ServiceClass ServiceClass;

#define TYPE_FILES (files_get_type ())
#define FILES(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_FILES, Files))
#define FILES_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_FILES, FilesClass))
#define IS_FILES(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_FILES))
#define IS_FILES_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_FILES))
#define FILES_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_FILES, FilesClass))

typedef struct _Files Files;
typedef struct _FilesClass FilesClass;

#define TYPE_WEATHER (weather_get_type ())
#define WEATHER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_WEATHER, Weather))
#define WEATHER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_WEATHER, WeatherClass))
#define IS_WEATHER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_WEATHER))
#define IS_WEATHER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_WEATHER))
#define WEATHER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_WEATHER, WeatherClass))

typedef struct _Weather Weather;
typedef struct _WeatherClass WeatherClass;

#define TYPE_NEWS (news_get_type ())
#define NEWS(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_NEWS, News))
#define NEWS_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_NEWS, NewsClass))
#define IS_NEWS(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_NEWS))
#define IS_NEWS_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_NEWS))
#define NEWS_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_NEWS, NewsClass))

typedef struct _News News;
typedef struct _NewsClass NewsClass;

struct _GlobalSettings {
	GraniteServicesSettings parent_instance;
	GlobalSettingsPrivate * priv;
};

struct _GlobalSettingsClass {
	GraniteServicesSettingsClass parent_class;
};

struct _GlobalSettingsPrivate {
	gchar** _services_enabled;
	gint _services_enabled_length1;
	gint __services_enabled_size_;
};

struct _Gazette {
	GraniteApplication parent_instance;
	GazettePrivate * priv;
};

struct _GazetteClass {
	GraniteApplicationClass parent_class;
};

struct _Block1Data {
	int _ref_count_;
	Gazette * self;
	GazetteWindow* window;
	gint* size;
	gint size_length1;
	gint _size_size_;
	ShadowedLabel* welcome;
	ShadowedLabel* randomline1;
	ShadowedLabel* randomline2;
};


static gpointer global_settings_parent_class = NULL;
static GlobalSettings* global_settings_instance;
static GlobalSettings* global_settings_instance = NULL;
static gpointer gazette_parent_class = NULL;

#define textcolor "blue"
GType global_settings_get_type (void) G_GNUC_CONST;
#define GLOBAL_SETTINGS_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), TYPE_GLOBAL_SETTINGS, GlobalSettingsPrivate))
enum  {
	GLOBAL_SETTINGS_DUMMY_PROPERTY,
	GLOBAL_SETTINGS_SERVICES_ENABLED
};
GlobalSettings* global_settings_new (void);
GlobalSettings* global_settings_construct (GType object_type);
GlobalSettings* global_settings_get_default (void);
gchar** global_settings_get_services_enabled (GlobalSettings* self, int* result_length1);
void global_settings_set_services_enabled (GlobalSettings* self, gchar** value, int value_length1);
static gchar** _vala_array_dup1 (gchar** self, int length);
static void global_settings_finalize (GObject* obj);
static void _vala_global_settings_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec);
static void _vala_global_settings_set_property (GObject * object, guint property_id, const GValue * value, GParamSpec * pspec);
GType gazette_get_type (void) G_GNUC_CONST;
enum  {
	GAZETTE_DUMMY_PROPERTY
};
#define GAZETTE_MARGIN 50
Gazette* gazette_new (void);
Gazette* gazette_construct (GType object_type);
static void gazette_real_activate (GApplication* base);
GType gazette_window_get_type (void) G_GNUC_CONST;
GType shadowed_label_get_type (void) G_GNUC_CONST;
static Block1Data* block1_data_ref (Block1Data* _data1_);
static void block1_data_unref (void * _userdata_);
GazetteWindow* gazette_window_new (void);
GazetteWindow* gazette_window_construct (GType object_type);
gint* gazette_window_reposition (GazetteWindow* self, int* result_length1);
ShadowedLabel* shadowed_label_new (const gchar* _label);
ShadowedLabel* shadowed_label_construct (GType object_type, const gchar* _label);
static void __lambda4_ (Block1Data* _data1_);
static void __lambda5_ (Block1Data* _data1_);
static void ___lambda5__clutter_timeline_completed (ClutterTimeline* _sender, gpointer self);
static void ___lambda4__clutter_timeline_completed (ClutterTimeline* _sender, gpointer self);
ClutterStage* gazette_window_get_stage (GazetteWindow* self);
static void __lambda6_ (Block1Data* _data1_);
static void __lambda7_ (Block1Data* _data1_);
static void ___lambda7__clutter_timeline_completed (ClutterTimeline* _sender, gpointer self);
static void ___lambda6__clutter_timeline_completed (ClutterTimeline* _sender, gpointer self);
static void __lambda8_ (Block1Data* _data1_);
static void __lambda9_ (Block1Data* _data1_);
static void ___lambda9__clutter_timeline_completed (ClutterTimeline* _sender, gpointer self);
static void ___lambda8__clutter_timeline_completed (ClutterTimeline* _sender, gpointer self);
static gboolean __lambda10_ (Block1Data* _data1_);
static gchar** _vala_array_dup2 (gchar** self, int length);
static void gazette_parse_coords (Gazette* self, const gchar* service, gchar** id, gint* x, gint* y);
Files* files_new (void);
Files* files_construct (GType object_type);
GType service_get_type (void) G_GNUC_CONST;
GType files_get_type (void) G_GNUC_CONST;
Weather* weather_new (void);
Weather* weather_construct (GType object_type);
GType weather_get_type (void) G_GNUC_CONST;
News* news_new (void);
News* news_construct (GType object_type);
GType news_get_type (void) G_GNUC_CONST;
static gboolean ___lambda10__gsource_func (gpointer self);
static GObject * gazette_constructor (GType type, guint n_construct_properties, GObjectConstructParam * construct_properties);
gint _vala_main (gchar** args, int args_length1);
static void _vala_array_destroy (gpointer array, gint array_length, GDestroyNotify destroy_func);
static void _vala_array_free (gpointer array, gint array_length, GDestroyNotify destroy_func);
static gint _vala_array_length (gpointer array);


GlobalSettings* global_settings_construct (GType object_type) {
	GlobalSettings * self = NULL;
	self = (GlobalSettings*) granite_services_settings_construct (object_type, "org.pantheon.gazette");
	return self;
}


GlobalSettings* global_settings_new (void) {
	return global_settings_construct (TYPE_GLOBAL_SETTINGS);
}


static gpointer _g_object_ref0 (gpointer self) {
	return self ? g_object_ref (self) : NULL;
}


GlobalSettings* global_settings_get_default (void) {
	GlobalSettings* result = NULL;
	GlobalSettings* _tmp0_;
	GlobalSettings* _tmp2_;
	GlobalSettings* _tmp3_;
	_tmp0_ = global_settings_instance;
	if (_tmp0_ == NULL) {
		GlobalSettings* _tmp1_;
		_tmp1_ = global_settings_new ();
		_g_object_unref0 (global_settings_instance);
		global_settings_instance = _tmp1_;
	}
	_tmp2_ = global_settings_instance;
	_tmp3_ = _g_object_ref0 (_tmp2_);
	result = _tmp3_;
	return result;
}


gchar** global_settings_get_services_enabled (GlobalSettings* self, int* result_length1) {
	gchar** result;
	gchar** _tmp0_;
	gint _tmp0__length1;
	gchar** _tmp1_;
	gint _tmp1__length1;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->_services_enabled;
	_tmp0__length1 = self->priv->_services_enabled_length1;
	_tmp1_ = _tmp0_;
	_tmp1__length1 = _tmp0__length1;
	if (result_length1) {
		*result_length1 = _tmp1__length1;
	}
	result = _tmp1_;
	return result;
}


static gchar** _vala_array_dup1 (gchar** self, int length) {
	gchar** result;
	int i;
	result = g_new0 (gchar*, length + 1);
	for (i = 0; i < length; i++) {
		gchar* _tmp0_;
		_tmp0_ = g_strdup (self[i]);
		result[i] = _tmp0_;
	}
	return result;
}


void global_settings_set_services_enabled (GlobalSettings* self, gchar** value, int value_length1) {
	gchar** _tmp0_;
	gint _tmp0__length1;
	gchar** _tmp1_;
	gint _tmp1__length1;
	g_return_if_fail (self != NULL);
	_tmp0_ = value;
	_tmp0__length1 = value_length1;
	_tmp1_ = (_tmp0_ != NULL) ? _vala_array_dup1 (_tmp0_, _tmp0__length1) : ((gpointer) _tmp0_);
	_tmp1__length1 = _tmp0__length1;
	self->priv->_services_enabled = (_vala_array_free (self->priv->_services_enabled, self->priv->_services_enabled_length1, (GDestroyNotify) g_free), NULL);
	self->priv->_services_enabled = _tmp1_;
	self->priv->_services_enabled_length1 = _tmp1__length1;
	self->priv->__services_enabled_size_ = self->priv->_services_enabled_length1;
	g_object_notify ((GObject *) self, "services-enabled");
}


static void global_settings_class_init (GlobalSettingsClass * klass) {
	global_settings_parent_class = g_type_class_peek_parent (klass);
	g_type_class_add_private (klass, sizeof (GlobalSettingsPrivate));
	G_OBJECT_CLASS (klass)->get_property = _vala_global_settings_get_property;
	G_OBJECT_CLASS (klass)->set_property = _vala_global_settings_set_property;
	G_OBJECT_CLASS (klass)->finalize = global_settings_finalize;
	g_object_class_install_property (G_OBJECT_CLASS (klass), GLOBAL_SETTINGS_SERVICES_ENABLED, g_param_spec_boxed ("services-enabled", "services-enabled", "services-enabled", G_TYPE_STRV, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
}


static void global_settings_instance_init (GlobalSettings * self) {
	self->priv = GLOBAL_SETTINGS_GET_PRIVATE (self);
}


static void global_settings_finalize (GObject* obj) {
	GlobalSettings * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, TYPE_GLOBAL_SETTINGS, GlobalSettings);
	self->priv->_services_enabled = (_vala_array_free (self->priv->_services_enabled, self->priv->_services_enabled_length1, (GDestroyNotify) g_free), NULL);
	G_OBJECT_CLASS (global_settings_parent_class)->finalize (obj);
}


GType global_settings_get_type (void) {
	static volatile gsize global_settings_type_id__volatile = 0;
	if (g_once_init_enter (&global_settings_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (GlobalSettingsClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) global_settings_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (GlobalSettings), 0, (GInstanceInitFunc) global_settings_instance_init, NULL };
		GType global_settings_type_id;
		global_settings_type_id = g_type_register_static (GRANITE_SERVICES_TYPE_SETTINGS, "GlobalSettings", &g_define_type_info, 0);
		g_once_init_leave (&global_settings_type_id__volatile, global_settings_type_id);
	}
	return global_settings_type_id__volatile;
}


static void _vala_global_settings_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec) {
	GlobalSettings * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, TYPE_GLOBAL_SETTINGS, GlobalSettings);
	switch (property_id) {
		case GLOBAL_SETTINGS_SERVICES_ENABLED:
		{
			int length;
			g_value_set_boxed (value, global_settings_get_services_enabled (self, &length));
		}
		break;
		default:
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}


static void _vala_global_settings_set_property (GObject * object, guint property_id, const GValue * value, GParamSpec * pspec) {
	GlobalSettings * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, TYPE_GLOBAL_SETTINGS, GlobalSettings);
	switch (property_id) {
		case GLOBAL_SETTINGS_SERVICES_ENABLED:
		{
			gpointer boxed;
			boxed = g_value_get_boxed (value);
			global_settings_set_services_enabled (self, boxed, g_strv_length (boxed));
		}
		break;
		default:
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}


Gazette* gazette_construct (GType object_type) {
	Gazette * self = NULL;
	self = (Gazette*) granite_application_construct (object_type);
	return self;
}


Gazette* gazette_new (void) {
	return gazette_construct (TYPE_GAZETTE);
}


static Block1Data* block1_data_ref (Block1Data* _data1_) {
	g_atomic_int_inc (&_data1_->_ref_count_);
	return _data1_;
}


static void block1_data_unref (void * _userdata_) {
	Block1Data* _data1_;
	_data1_ = (Block1Data*) _userdata_;
	if (g_atomic_int_dec_and_test (&_data1_->_ref_count_)) {
		Gazette * self;
		self = _data1_->self;
		_g_object_unref0 (_data1_->randomline2);
		_g_object_unref0 (_data1_->randomline1);
		_g_object_unref0 (_data1_->welcome);
		_data1_->size = (g_free (_data1_->size), NULL);
		_g_object_unref0 (_data1_->window);
		_g_object_unref0 (self);
		g_slice_free (Block1Data, _data1_);
	}
}


static void __lambda5_ (Block1Data* _data1_) {
	Gazette * self;
	ShadowedLabel* _tmp0_;
	self = _data1_->self;
	_tmp0_ = _data1_->welcome;
	clutter_actor_animate ((ClutterActor*) _tmp0_, (gulong) CLUTTER_LINEAR, (guint) 500, "x", 250.0f, "opacity", 0, NULL);
}


static void ___lambda5__clutter_timeline_completed (ClutterTimeline* _sender, gpointer self) {
	__lambda5_ (self);
}


static void __lambda4_ (Block1Data* _data1_) {
	Gazette * self;
	ShadowedLabel* _tmp0_;
	ClutterAnimation* _tmp1_ = NULL;
	ClutterTimeline* _tmp2_ = NULL;
	self = _data1_->self;
	_tmp0_ = _data1_->welcome;
	_tmp1_ = clutter_actor_animate ((ClutterActor*) _tmp0_, (gulong) CLUTTER_LINEAR, (guint) 1000, "x", 200.0f, NULL);
	_tmp2_ = clutter_animation_get_timeline (_tmp1_);
	g_signal_connect_data (_tmp2_, "completed", (GCallback) ___lambda5__clutter_timeline_completed, block1_data_ref (_data1_), (GClosureNotify) block1_data_unref, 0);
}


static void ___lambda4__clutter_timeline_completed (ClutterTimeline* _sender, gpointer self) {
	__lambda4_ (self);
}


static void __lambda7_ (Block1Data* _data1_) {
	Gazette * self;
	ShadowedLabel* _tmp0_;
	self = _data1_->self;
	_tmp0_ = _data1_->randomline1;
	clutter_actor_animate ((ClutterActor*) _tmp0_, (gulong) CLUTTER_EASE_OUT_QUAD, (guint) 1000, "x", 50.0f, "opacity", 0, NULL);
}


static void ___lambda7__clutter_timeline_completed (ClutterTimeline* _sender, gpointer self) {
	__lambda7_ (self);
}


static void __lambda6_ (Block1Data* _data1_) {
	Gazette * self;
	ShadowedLabel* _tmp0_;
	ClutterAnimation* _tmp1_ = NULL;
	ClutterTimeline* _tmp2_ = NULL;
	self = _data1_->self;
	_tmp0_ = _data1_->randomline1;
	_tmp1_ = clutter_actor_animate ((ClutterActor*) _tmp0_, (gulong) CLUTTER_LINEAR, (guint) 10, "x", 75.0f, NULL);
	_tmp2_ = clutter_animation_get_timeline (_tmp1_);
	g_signal_connect_data (_tmp2_, "completed", (GCallback) ___lambda7__clutter_timeline_completed, block1_data_ref (_data1_), (GClosureNotify) block1_data_unref, 0);
}


static void ___lambda6__clutter_timeline_completed (ClutterTimeline* _sender, gpointer self) {
	__lambda6_ (self);
}


static void __lambda9_ (Block1Data* _data1_) {
	Gazette * self;
	ShadowedLabel* _tmp0_;
	self = _data1_->self;
	_tmp0_ = _data1_->randomline2;
	clutter_actor_animate ((ClutterActor*) _tmp0_, (gulong) CLUTTER_EASE_OUT_QUAD, (guint) 1000, "x", 760.0f, "opacity", 0, NULL);
}


static void ___lambda9__clutter_timeline_completed (ClutterTimeline* _sender, gpointer self) {
	__lambda9_ (self);
}


static void __lambda8_ (Block1Data* _data1_) {
	Gazette * self;
	ShadowedLabel* _tmp0_;
	ClutterAnimation* _tmp1_ = NULL;
	ClutterTimeline* _tmp2_ = NULL;
	self = _data1_->self;
	_tmp0_ = _data1_->randomline2;
	_tmp1_ = clutter_actor_animate ((ClutterActor*) _tmp0_, (gulong) CLUTTER_LINEAR, (guint) 1, "x", 700.0f, NULL);
	_tmp2_ = clutter_animation_get_timeline (_tmp1_);
	g_signal_connect_data (_tmp2_, "completed", (GCallback) ___lambda9__clutter_timeline_completed, block1_data_ref (_data1_), (GClosureNotify) block1_data_unref, 0);
}


static void ___lambda8__clutter_timeline_completed (ClutterTimeline* _sender, gpointer self) {
	__lambda8_ (self);
}


static gchar** _vala_array_dup2 (gchar** self, int length) {
	gchar** result;
	int i;
	result = g_new0 (gchar*, length + 1);
	for (i = 0; i < length; i++) {
		gchar* _tmp0_;
		_tmp0_ = g_strdup (self[i]);
		result[i] = _tmp0_;
	}
	return result;
}


static gboolean __lambda10_ (Block1Data* _data1_) {
	Gazette * self;
	gboolean result = FALSE;
	GlobalSettings* _tmp0_ = NULL;
	GlobalSettings* _tmp1_;
	gchar** _tmp2_;
	gint _tmp2__length1;
	gchar** _tmp3_;
	gint _tmp3__length1;
	gchar** _tmp4_;
	gint _tmp4__length1;
	gchar** _tmp5_;
	gint _tmp5__length1;
	gchar** list;
	gint list_length1;
	gint _list_size_;
	self = _data1_->self;
	_tmp0_ = global_settings_get_default ();
	_tmp1_ = _tmp0_;
	_tmp2_ = global_settings_get_services_enabled (_tmp1_, &_tmp2__length1);
	_tmp3_ = _tmp2_;
	_tmp3__length1 = _tmp2__length1;
	_tmp4_ = (_tmp3_ != NULL) ? _vala_array_dup2 (_tmp3_, _tmp3__length1) : ((gpointer) _tmp3_);
	_tmp4__length1 = _tmp3__length1;
	_tmp5_ = _tmp4_;
	_tmp5__length1 = _tmp4__length1;
	_g_object_unref0 (_tmp1_);
	list = _tmp5_;
	list_length1 = _tmp5__length1;
	_list_size_ = list_length1;
	{
		gint i;
		i = 0;
		{
			gboolean _tmp6_;
			_tmp6_ = TRUE;
			while (TRUE) {
				gboolean _tmp7_;
				gint _tmp9_;
				gchar** _tmp10_;
				gint _tmp10__length1;
				gchar* id = NULL;
				gint x = 0;
				gint y = 0;
				gchar** _tmp11_;
				gint _tmp11__length1;
				gint _tmp12_;
				const gchar* _tmp13_;
				gchar* _tmp14_ = NULL;
				gint _tmp15_ = 0;
				gint _tmp16_ = 0;
				const gchar* _tmp17_;
				const gchar* _tmp18_;
				GQuark _tmp20_ = 0U;
				static GQuark _tmp19_label0 = 0;
				static GQuark _tmp19_label1 = 0;
				static GQuark _tmp19_label2 = 0;
				_tmp7_ = _tmp6_;
				if (!_tmp7_) {
					gint _tmp8_;
					_tmp8_ = i;
					i = _tmp8_ + 1;
				}
				_tmp6_ = FALSE;
				_tmp9_ = i;
				_tmp10_ = list;
				_tmp10__length1 = list_length1;
				if (!(_tmp9_ < _tmp10__length1)) {
					break;
				}
				_tmp11_ = list;
				_tmp11__length1 = list_length1;
				_tmp12_ = i;
				_tmp13_ = _tmp11_[_tmp12_];
				gazette_parse_coords (self, _tmp13_, &_tmp14_, &_tmp15_, &_tmp16_);
				_g_free0 (id);
				id = _tmp14_;
				x = _tmp15_;
				y = _tmp16_;
				_tmp17_ = id;
				_tmp18_ = _tmp17_;
				_tmp20_ = (NULL == _tmp18_) ? 0 : g_quark_from_string (_tmp18_);
				if (_tmp20_ == ((0 != _tmp19_label0) ? _tmp19_label0 : (_tmp19_label0 = g_quark_from_static_string ("files")))) {
					switch (0) {
						default:
						{
							Files* _tmp21_;
							Files* files;
							gint _tmp22_ = 0;
							gint _tmp23_;
							Files* _tmp27_;
							gint _tmp28_;
							gint _tmp29_ = 0;
							gint _tmp30_;
							Files* _tmp32_;
							gint _tmp33_;
							GazetteWindow* _tmp34_;
							ClutterStage* _tmp35_;
							ClutterStage* _tmp36_;
							Files* _tmp37_;
							_tmp21_ = files_new ();
							g_object_ref_sink (_tmp21_);
							files = _tmp21_;
							_tmp23_ = x;
							if (_tmp23_ > 0) {
								gint _tmp24_;
								_tmp24_ = x;
								_tmp22_ = _tmp24_;
							} else {
								gint* _tmp25_;
								gint _tmp25__length1;
								gint _tmp26_;
								_tmp25_ = _data1_->size;
								_tmp25__length1 = _data1_->size_length1;
								_tmp26_ = _tmp25_[0];
								_tmp22_ = (_tmp26_ - GAZETTE_MARGIN) - 340;
							}
							_tmp27_ = files;
							_tmp28_ = _tmp22_;
							clutter_actor_set_x ((ClutterActor*) _tmp27_, (gfloat) _tmp28_);
							_tmp30_ = y;
							if (_tmp30_ > 0) {
								gint _tmp31_;
								_tmp31_ = y;
								_tmp29_ = _tmp31_;
							} else {
								_tmp29_ = GAZETTE_MARGIN + 260;
							}
							_tmp32_ = files;
							_tmp33_ = _tmp29_;
							clutter_actor_set_y ((ClutterActor*) _tmp32_, (gfloat) _tmp33_);
							_tmp34_ = _data1_->window;
							_tmp35_ = gazette_window_get_stage (_tmp34_);
							_tmp36_ = _tmp35_;
							_tmp37_ = files;
							clutter_actor_add_child ((ClutterActor*) _tmp36_, (ClutterActor*) _tmp37_);
							_g_object_unref0 (files);
							break;
						}
					}
				} else if (_tmp20_ == ((0 != _tmp19_label1) ? _tmp19_label1 : (_tmp19_label1 = g_quark_from_static_string ("weather")))) {
					switch (0) {
						default:
						{
							Weather* _tmp38_;
							Weather* weather;
							gint _tmp39_ = 0;
							gint _tmp40_;
							Weather* _tmp44_;
							gint _tmp45_;
							gint _tmp46_ = 0;
							gint _tmp47_;
							Weather* _tmp49_;
							gint _tmp50_;
							GazetteWindow* _tmp51_;
							ClutterStage* _tmp52_;
							ClutterStage* _tmp53_;
							Weather* _tmp54_;
							_tmp38_ = weather_new ();
							g_object_ref_sink (_tmp38_);
							weather = _tmp38_;
							_tmp40_ = x;
							if (_tmp40_ > 0) {
								gint _tmp41_;
								_tmp41_ = x;
								_tmp39_ = _tmp41_;
							} else {
								gint* _tmp42_;
								gint _tmp42__length1;
								gint _tmp43_;
								_tmp42_ = _data1_->size;
								_tmp42__length1 = _data1_->size_length1;
								_tmp43_ = _tmp42_[0];
								_tmp39_ = (_tmp43_ - GAZETTE_MARGIN) - 340;
							}
							_tmp44_ = weather;
							_tmp45_ = _tmp39_;
							clutter_actor_set_x ((ClutterActor*) _tmp44_, (gfloat) _tmp45_);
							_tmp47_ = y;
							if (_tmp47_ > 0) {
								gint _tmp48_;
								_tmp48_ = y;
								_tmp46_ = _tmp48_;
							} else {
								_tmp46_ = GAZETTE_MARGIN;
							}
							_tmp49_ = weather;
							_tmp50_ = _tmp46_;
							clutter_actor_set_y ((ClutterActor*) _tmp49_, (gfloat) _tmp50_);
							_tmp51_ = _data1_->window;
							_tmp52_ = gazette_window_get_stage (_tmp51_);
							_tmp53_ = _tmp52_;
							_tmp54_ = weather;
							clutter_actor_add_child ((ClutterActor*) _tmp53_, (ClutterActor*) _tmp54_);
							_g_object_unref0 (weather);
							break;
						}
					}
				} else if (_tmp20_ == ((0 != _tmp19_label2) ? _tmp19_label2 : (_tmp19_label2 = g_quark_from_static_string ("news")))) {
					switch (0) {
						default:
						{
							News* _tmp55_;
							News* news;
							gint _tmp56_ = 0;
							gint _tmp57_;
							News* _tmp61_;
							gint _tmp62_;
							gint _tmp63_ = 0;
							gint _tmp64_;
							News* _tmp66_;
							gint _tmp67_;
							GazetteWindow* _tmp68_;
							ClutterStage* _tmp69_;
							ClutterStage* _tmp70_;
							News* _tmp71_;
							_tmp55_ = news_new ();
							g_object_ref_sink (_tmp55_);
							news = _tmp55_;
							_tmp57_ = x;
							if (_tmp57_ > 0) {
								gint _tmp58_;
								_tmp58_ = x;
								_tmp56_ = _tmp58_;
							} else {
								gint* _tmp59_;
								gint _tmp59__length1;
								gint _tmp60_;
								_tmp59_ = _data1_->size;
								_tmp59__length1 = _data1_->size_length1;
								_tmp60_ = _tmp59_[0];
								_tmp56_ = (_tmp60_ - GAZETTE_MARGIN) - 340;
							}
							_tmp61_ = news;
							_tmp62_ = _tmp56_;
							clutter_actor_set_x ((ClutterActor*) _tmp61_, (gfloat) _tmp62_);
							_tmp64_ = y;
							if (_tmp64_ > 0) {
								gint _tmp65_;
								_tmp65_ = y;
								_tmp63_ = _tmp65_;
							} else {
								_tmp63_ = GAZETTE_MARGIN + 560;
							}
							_tmp66_ = news;
							_tmp67_ = _tmp63_;
							clutter_actor_set_y ((ClutterActor*) _tmp66_, (gfloat) _tmp67_);
							_tmp68_ = _data1_->window;
							_tmp69_ = gazette_window_get_stage (_tmp68_);
							_tmp70_ = _tmp69_;
							_tmp71_ = news;
							clutter_actor_add_child ((ClutterActor*) _tmp70_, (ClutterActor*) _tmp71_);
							_g_object_unref0 (news);
							break;
						}
					}
				} else {
					switch (0) {
						default:
						{
							g_warning ("Gazette.vala:114: Unrecognized service requested!");
							break;
						}
					}
				}
				_g_free0 (id);
			}
		}
	}
	result = FALSE;
	list = (_vala_array_free (list, list_length1, (GDestroyNotify) g_free), NULL);
	return result;
}


static gboolean ___lambda10__gsource_func (gpointer self) {
	gboolean result;
	result = __lambda10_ (self);
	return result;
}


static void gazette_real_activate (GApplication* base) {
	Gazette * self;
	Block1Data* _data1_;
	GList* _tmp0_ = NULL;
	guint _tmp1_ = 0U;
	GazetteWindow* _tmp2_;
	GazetteWindow* _tmp3_;
	GazetteWindow* _tmp4_;
	gint _tmp5_ = 0;
	gint* _tmp6_ = NULL;
	GazetteWindow* _tmp7_;
	const gchar* _tmp8_ = NULL;
	gchar* _tmp9_ = NULL;
	gchar* _tmp10_;
	const gchar* _tmp11_ = NULL;
	gchar* _tmp12_;
	gchar* _tmp13_;
	const gchar* _tmp14_ = NULL;
	gchar* _tmp15_;
	gchar* _tmp16_;
	gchar* _tmp17_ = NULL;
	gchar* _tmp18_;
	gchar* _tmp19_;
	gchar* _tmp20_;
	ShadowedLabel* _tmp21_;
	ShadowedLabel* _tmp22_;
	ShadowedLabel* _tmp23_;
	ShadowedLabel* _tmp24_;
	ShadowedLabel* _tmp25_;
	ShadowedLabel* _tmp26_;
	ClutterAnimation* _tmp27_ = NULL;
	ClutterTimeline* _tmp28_ = NULL;
	GazetteWindow* _tmp29_;
	ClutterStage* _tmp30_;
	ClutterStage* _tmp31_;
	ShadowedLabel* _tmp32_;
	gchar* _tmp33_;
	gchar* randomlinetext;
	const gchar* _tmp34_ = NULL;
	gchar* _tmp35_ = NULL;
	gchar* _tmp36_;
	const gchar* _tmp37_;
	const gchar* _tmp38_ = NULL;
	gchar* _tmp39_ = NULL;
	gchar* _tmp40_;
	gchar* _tmp41_;
	gchar* _tmp42_;
	ShadowedLabel* _tmp43_;
	ShadowedLabel* _tmp44_;
	ShadowedLabel* _tmp45_;
	ShadowedLabel* _tmp46_;
	ShadowedLabel* _tmp47_;
	ShadowedLabel* _tmp48_;
	ShadowedLabel* _tmp49_;
	gfloat _tmp50_;
	gfloat _tmp51_;
	ShadowedLabel* _tmp52_;
	gfloat _tmp53_;
	gfloat _tmp54_;
	ShadowedLabel* _tmp55_;
	ClutterAnimation* _tmp56_ = NULL;
	ClutterTimeline* _tmp57_ = NULL;
	GazetteWindow* _tmp58_;
	ClutterStage* _tmp59_;
	ClutterStage* _tmp60_;
	ShadowedLabel* _tmp61_;
	const gchar* _tmp62_ = NULL;
	gchar* _tmp63_ = NULL;
	gchar* _tmp64_;
	const gchar* _tmp65_;
	const gchar* _tmp66_ = NULL;
	gchar* _tmp67_ = NULL;
	gchar* _tmp68_;
	gchar* _tmp69_;
	gchar* _tmp70_;
	ShadowedLabel* _tmp71_;
	ShadowedLabel* _tmp72_;
	ShadowedLabel* _tmp73_;
	ShadowedLabel* _tmp74_;
	ShadowedLabel* _tmp75_;
	ShadowedLabel* _tmp76_;
	ShadowedLabel* _tmp77_;
	gfloat _tmp78_;
	gfloat _tmp79_;
	ShadowedLabel* _tmp80_;
	gfloat _tmp81_;
	gfloat _tmp82_;
	ShadowedLabel* _tmp83_;
	ClutterAnimation* _tmp84_ = NULL;
	ClutterTimeline* _tmp85_ = NULL;
	GazetteWindow* _tmp86_;
	ClutterStage* _tmp87_;
	ClutterStage* _tmp88_;
	ShadowedLabel* _tmp89_;
	self = (Gazette*) base;
	_data1_ = g_slice_new0 (Block1Data);
	_data1_->_ref_count_ = 1;
	_data1_->self = g_object_ref (self);
	_tmp0_ = gtk_application_get_windows ((GtkApplication*) self);
	_tmp1_ = g_list_length (_tmp0_);
	if (_tmp1_ > ((guint) 0)) {
		block1_data_unref (_data1_);
		_data1_ = NULL;
		return;
	}
	_tmp2_ = gazette_window_new ();
	g_object_ref_sink (_tmp2_);
	_data1_->window = _tmp2_;
	_tmp3_ = _data1_->window;
	gtk_window_set_application ((GtkWindow*) _tmp3_, (GtkApplication*) self);
	_tmp4_ = _data1_->window;
	_tmp6_ = gazette_window_reposition (_tmp4_, &_tmp5_);
	_data1_->size = _tmp6_;
	_data1_->size_length1 = _tmp5_;
	_data1_->_size_size_ = _data1_->size_length1;
	_tmp7_ = _data1_->window;
	gtk_widget_show_all ((GtkWidget*) _tmp7_);
	_tmp8_ = _ (textcolor);
	_tmp9_ = g_strdup_printf ("<span font='50' face='Raleway' color='%s'", _tmp8_);
	_tmp10_ = _tmp9_;
	_tmp11_ = _ ("Welcome");
	_tmp12_ = g_strconcat (_tmp11_, ", ", NULL);
	_tmp13_ = _tmp12_;
	_tmp14_ = g_get_real_name ();
	_tmp15_ = g_strconcat (_tmp13_, _tmp14_, NULL);
	_tmp16_ = _tmp15_;
	_tmp17_ = g_strdup_printf (">%s</span>", _tmp16_);
	_tmp18_ = _tmp17_;
	_tmp19_ = g_strconcat (_tmp10_, _tmp18_, NULL);
	_tmp20_ = _tmp19_;
	_tmp21_ = shadowed_label_new (_tmp20_);
	g_object_ref_sink (_tmp21_);
	_tmp22_ = _tmp21_;
	_g_free0 (_tmp20_);
	_g_free0 (_tmp18_);
	_g_free0 (_tmp16_);
	_g_free0 (_tmp13_);
	_g_free0 (_tmp10_);
	_data1_->welcome = _tmp22_;
	_tmp23_ = _data1_->welcome;
	clutter_actor_set_x ((ClutterActor*) _tmp23_, (gfloat) 50);
	_tmp24_ = _data1_->welcome;
	clutter_actor_set_y ((ClutterActor*) _tmp24_, (gfloat) 200);
	_tmp25_ = _data1_->welcome;
	clutter_actor_set_opacity ((ClutterActor*) _tmp25_, (guint) 0);
	_tmp26_ = _data1_->welcome;
	_tmp27_ = clutter_actor_animate ((ClutterActor*) _tmp26_, (gulong) CLUTTER_LINEAR, (guint) 500, "opacity", 255, "x", 100.0f, NULL);
	_tmp28_ = clutter_animation_get_timeline (_tmp27_);
	g_signal_connect_data (_tmp28_, "completed", (GCallback) ___lambda4__clutter_timeline_completed, block1_data_ref (_data1_), (GClosureNotify) block1_data_unref, 0);
	_tmp29_ = _data1_->window;
	_tmp30_ = gazette_window_get_stage (_tmp29_);
	_tmp31_ = _tmp30_;
	_tmp32_ = _data1_->welcome;
	clutter_actor_add_child ((ClutterActor*) _tmp31_, (ClutterActor*) _tmp32_);
	_tmp33_ = g_strdup ("______________________________________");
	randomlinetext = _tmp33_;
	_tmp34_ = _ (textcolor);
	_tmp35_ = g_strdup_printf ("<span font='10' face='FreeMono' color='%s'", _tmp34_);
	_tmp36_ = _tmp35_;
	_tmp37_ = randomlinetext;
	_tmp38_ = _ (_tmp37_);
	_tmp39_ = g_strdup_printf (">%s</span>", _tmp38_);
	_tmp40_ = _tmp39_;
	_tmp41_ = g_strconcat (_tmp36_, _tmp40_, NULL);
	_tmp42_ = _tmp41_;
	_tmp43_ = shadowed_label_new (_tmp42_);
	g_object_ref_sink (_tmp43_);
	_tmp44_ = _tmp43_;
	_g_free0 (_tmp42_);
	_g_free0 (_tmp40_);
	_g_free0 (_tmp36_);
	_data1_->randomline1 = _tmp44_;
	_tmp45_ = _data1_->randomline1;
	clutter_actor_set_x ((ClutterActor*) _tmp45_, (gfloat) 760);
	_tmp46_ = _data1_->randomline1;
	clutter_actor_set_y ((ClutterActor*) _tmp46_, (gfloat) 260);
	_tmp47_ = _data1_->randomline1;
	clutter_actor_set_opacity ((ClutterActor*) _tmp47_, (guint) 0);
	_tmp48_ = _data1_->randomline1;
	_tmp49_ = _data1_->welcome;
	_tmp50_ = clutter_actor_get_width ((ClutterActor*) _tmp49_);
	_tmp51_ = _tmp50_;
	_tmp52_ = _data1_->randomline1;
	_tmp53_ = clutter_actor_get_width ((ClutterActor*) _tmp52_);
	_tmp54_ = _tmp53_;
	g_object_set ((ClutterActor*) _tmp48_, "scale-x", (gdouble) (_tmp51_ / _tmp54_), NULL);
	_tmp55_ = _data1_->randomline1;
	_tmp56_ = clutter_actor_animate ((ClutterActor*) _tmp55_, (gulong) CLUTTER_EASE_IN_QUAD, (guint) 900, "opacity", 255, "x", 100.0f, NULL);
	_tmp57_ = clutter_animation_get_timeline (_tmp56_);
	g_signal_connect_data (_tmp57_, "completed", (GCallback) ___lambda6__clutter_timeline_completed, block1_data_ref (_data1_), (GClosureNotify) block1_data_unref, 0);
	_tmp58_ = _data1_->window;
	_tmp59_ = gazette_window_get_stage (_tmp58_);
	_tmp60_ = _tmp59_;
	_tmp61_ = _data1_->randomline1;
	clutter_actor_add_child ((ClutterActor*) _tmp60_, (ClutterActor*) _tmp61_);
	_tmp62_ = _ (textcolor);
	_tmp63_ = g_strdup_printf ("<span font='10' face='FreeMono' color='%s'", _tmp62_);
	_tmp64_ = _tmp63_;
	_tmp65_ = randomlinetext;
	_tmp66_ = _ (_tmp65_);
	_tmp67_ = g_strdup_printf (">%s</span>", _tmp66_);
	_tmp68_ = _tmp67_;
	_tmp69_ = g_strconcat (_tmp64_, _tmp68_, NULL);
	_tmp70_ = _tmp69_;
	_tmp71_ = shadowed_label_new (_tmp70_);
	g_object_ref_sink (_tmp71_);
	_tmp72_ = _tmp71_;
	_g_free0 (_tmp70_);
	_g_free0 (_tmp68_);
	_g_free0 (_tmp64_);
	_data1_->randomline2 = _tmp72_;
	_tmp73_ = _data1_->randomline2;
	clutter_actor_set_x ((ClutterActor*) _tmp73_, (gfloat) 50);
	_tmp74_ = _data1_->randomline2;
	clutter_actor_set_y ((ClutterActor*) _tmp74_, (gfloat) 195);
	_tmp75_ = _data1_->randomline2;
	clutter_actor_set_opacity ((ClutterActor*) _tmp75_, (guint) 0);
	_tmp76_ = _data1_->randomline2;
	_tmp77_ = _data1_->welcome;
	_tmp78_ = clutter_actor_get_width ((ClutterActor*) _tmp77_);
	_tmp79_ = _tmp78_;
	_tmp80_ = _data1_->randomline2;
	_tmp81_ = clutter_actor_get_width ((ClutterActor*) _tmp80_);
	_tmp82_ = _tmp81_;
	g_object_set ((ClutterActor*) _tmp76_, "scale-x", (gdouble) (_tmp79_ / _tmp82_), NULL);
	_tmp83_ = _data1_->randomline2;
	_tmp84_ = clutter_actor_animate ((ClutterActor*) _tmp83_, (gulong) CLUTTER_EASE_IN_QUAD, (guint) 700, "opacity", 255, "x", 600.0f, NULL);
	_tmp85_ = clutter_animation_get_timeline (_tmp84_);
	g_signal_connect_data (_tmp85_, "completed", (GCallback) ___lambda8__clutter_timeline_completed, block1_data_ref (_data1_), (GClosureNotify) block1_data_unref, 0);
	_tmp86_ = _data1_->window;
	_tmp87_ = gazette_window_get_stage (_tmp86_);
	_tmp88_ = _tmp87_;
	_tmp89_ = _data1_->randomline2;
	clutter_actor_add_child ((ClutterActor*) _tmp88_, (ClutterActor*) _tmp89_);
	g_timeout_add_full (G_PRIORITY_DEFAULT, (guint) 2000, ___lambda10__gsource_func, block1_data_ref (_data1_), block1_data_unref);
	_g_free0 (randomlinetext);
	block1_data_unref (_data1_);
	_data1_ = NULL;
}


static void gazette_parse_coords (Gazette* self, const gchar* service, gchar** id, gint* x, gint* y) {
	gchar* _vala_id = NULL;
	gint _vala_x = 0;
	gint _vala_y = 0;
	const gchar* _tmp0_;
	gchar** _tmp1_;
	gchar** _tmp2_ = NULL;
	gchar** parts;
	gint parts_length1;
	gint _parts_size_;
	gchar** _tmp3_;
	gint _tmp3__length1;
	const gchar* _tmp4_;
	gchar* _tmp5_;
	gchar** _tmp6_;
	gint _tmp6__length1;
	gchar** _tmp7_;
	gint _tmp7__length1;
	const gchar* _tmp8_;
	gchar** _tmp9_;
	gchar** _tmp10_ = NULL;
	gchar** coords;
	gint coords_length1;
	gint _coords_size_;
	gchar** _tmp11_;
	gint _tmp11__length1;
	const gchar* _tmp12_;
	gint _tmp13_ = 0;
	gchar** _tmp14_;
	gint _tmp14__length1;
	const gchar* _tmp15_;
	gint _tmp16_ = 0;
	g_return_if_fail (self != NULL);
	g_return_if_fail (service != NULL);
	_tmp0_ = service;
	_tmp2_ = _tmp1_ = g_strsplit (_tmp0_, ":", 0);
	parts = _tmp2_;
	parts_length1 = _vala_array_length (_tmp1_);
	_parts_size_ = parts_length1;
	_tmp3_ = parts;
	_tmp3__length1 = parts_length1;
	_tmp4_ = _tmp3_[0];
	_tmp5_ = g_strdup (_tmp4_);
	_g_free0 (_vala_id);
	_vala_id = _tmp5_;
	_tmp6_ = parts;
	_tmp6__length1 = parts_length1;
	if (_tmp6__length1 < 2) {
		_vala_x = -1;
		_vala_y = -1;
		parts = (_vala_array_free (parts, parts_length1, (GDestroyNotify) g_free), NULL);
		if (id) {
			*id = _vala_id;
		} else {
			_g_free0 (_vala_id);
		}
		if (x) {
			*x = _vala_x;
		}
		if (y) {
			*y = _vala_y;
		}
		return;
	}
	_tmp7_ = parts;
	_tmp7__length1 = parts_length1;
	_tmp8_ = _tmp7_[1];
	_tmp10_ = _tmp9_ = g_strsplit (_tmp8_, ",", 0);
	coords = _tmp10_;
	coords_length1 = _vala_array_length (_tmp9_);
	_coords_size_ = coords_length1;
	_tmp11_ = coords;
	_tmp11__length1 = coords_length1;
	_tmp12_ = _tmp11_[0];
	_tmp13_ = atoi (_tmp12_);
	_vala_x = _tmp13_;
	_tmp14_ = coords;
	_tmp14__length1 = coords_length1;
	_tmp15_ = _tmp14_[1];
	_tmp16_ = atoi (_tmp15_);
	_vala_y = _tmp16_;
	coords = (_vala_array_free (coords, coords_length1, (GDestroyNotify) g_free), NULL);
	parts = (_vala_array_free (parts, parts_length1, (GDestroyNotify) g_free), NULL);
	if (id) {
		*id = _vala_id;
	} else {
		_g_free0 (_vala_id);
	}
	if (x) {
		*x = _vala_x;
	}
	if (y) {
		*y = _vala_y;
	}
}


static GObject * gazette_constructor (GType type, guint n_construct_properties, GObjectConstructParam * construct_properties) {
	GObject * obj;
	GObjectClass * parent_class;
	Gazette * self;
	gchar* _tmp0_;
	parent_class = G_OBJECT_CLASS (gazette_parent_class);
	obj = parent_class->constructor (type, n_construct_properties, construct_properties);
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, TYPE_GAZETTE, Gazette);
	_tmp0_ = g_strdup ("Gazette");
	_g_free0 (((GraniteApplication*) self)->program_name);
	((GraniteApplication*) self)->program_name = _tmp0_;
	g_application_set_application_id ((GApplication*) self, "org.pantheon.gazette");
	return obj;
}


static void gazette_class_init (GazetteClass * klass) {
	gazette_parent_class = g_type_class_peek_parent (klass);
	G_APPLICATION_CLASS (klass)->activate = gazette_real_activate;
	G_OBJECT_CLASS (klass)->constructor = gazette_constructor;
}


static void gazette_instance_init (Gazette * self) {
}


GType gazette_get_type (void) {
	static volatile gsize gazette_type_id__volatile = 0;
	if (g_once_init_enter (&gazette_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (GazetteClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) gazette_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (Gazette), 0, (GInstanceInitFunc) gazette_instance_init, NULL };
		GType gazette_type_id;
		gazette_type_id = g_type_register_static (GRANITE_TYPE_APPLICATION, "Gazette", &g_define_type_info, 0);
		g_once_init_leave (&gazette_type_id__volatile, gazette_type_id);
	}
	return gazette_type_id__volatile;
}


gint _vala_main (gchar** args, int args_length1) {
	gint result = 0;
	Gazette* _tmp0_;
	Gazette* _tmp1_;
	gchar** _tmp2_;
	gint _tmp2__length1;
	gint _tmp3_ = 0;
	gint _tmp4_;
	gtk_clutter_init (&args_length1, &args);
	_tmp0_ = gazette_new ();
	_tmp1_ = _tmp0_;
	_tmp2_ = args;
	_tmp2__length1 = args_length1;
	_tmp3_ = granite_application_run ((GraniteApplication*) _tmp1_, _tmp2_, _tmp2__length1);
	_tmp4_ = _tmp3_;
	_g_object_unref0 (_tmp1_);
	result = _tmp4_;
	return result;
}


int main (int argc, char ** argv) {
	g_type_init ();
	return _vala_main (argv, argc);
}


static void _vala_array_destroy (gpointer array, gint array_length, GDestroyNotify destroy_func) {
	if ((array != NULL) && (destroy_func != NULL)) {
		int i;
		for (i = 0; i < array_length; i = i + 1) {
			if (((gpointer*) array)[i] != NULL) {
				destroy_func (((gpointer*) array)[i]);
			}
		}
	}
}


static void _vala_array_free (gpointer array, gint array_length, GDestroyNotify destroy_func) {
	_vala_array_destroy (array, array_length, destroy_func);
	g_free (array);
}


static gint _vala_array_length (gpointer array) {
	int length;
	length = 0;
	if (array) {
		while (((gpointer*) array)[length]) {
			length++;
		}
	}
	return length;
}



