/* GazetteWindow.c generated by valac 0.20.1, the Vala compiler
 * generated from GazetteWindow.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <granite.h>
#include <clutter-gtk/clutter-gtk.h>
#include <gtk/gtk.h>
#include <gdk/gdk.h>
#include <clutter/clutter.h>
#include <cairo.h>


#define TYPE_GAZETTE_WINDOW (gazette_window_get_type ())
#define GAZETTE_WINDOW(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_GAZETTE_WINDOW, GazetteWindow))
#define GAZETTE_WINDOW_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_GAZETTE_WINDOW, GazetteWindowClass))
#define IS_GAZETTE_WINDOW(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_GAZETTE_WINDOW))
#define IS_GAZETTE_WINDOW_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_GAZETTE_WINDOW))
#define GAZETTE_WINDOW_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_GAZETTE_WINDOW, GazetteWindowClass))

typedef struct _GazetteWindow GazetteWindow;
typedef struct _GazetteWindowClass GazetteWindowClass;
typedef struct _GazetteWindowPrivate GazetteWindowPrivate;
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))

struct _GazetteWindow {
	GraniteWidgetsCompositedWindow parent_instance;
	GazetteWindowPrivate * priv;
};

struct _GazetteWindowClass {
	GraniteWidgetsCompositedWindowClass parent_class;
};

struct _GazetteWindowPrivate {
	GtkClutterEmbed* embed;
};


static gpointer gazette_window_parent_class = NULL;

GType gazette_window_get_type (void) G_GNUC_CONST;
#define GAZETTE_WINDOW_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), TYPE_GAZETTE_WINDOW, GazetteWindowPrivate))
enum  {
	GAZETTE_WINDOW_DUMMY_PROPERTY,
	GAZETTE_WINDOW_STAGE
};
GazetteWindow* gazette_window_new (void);
GazetteWindow* gazette_window_construct (GType object_type);
ClutterStage* gazette_window_get_stage (GazetteWindow* self);
gint* gazette_window_reposition (GazetteWindow* self, int* result_length1);
static void gazette_window_set_stage (GazetteWindow* self, ClutterStage* value);
static void gazette_window_finalize (GObject* obj);
static void _vala_gazette_window_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec);
static void _vala_gazette_window_set_property (GObject * object, guint property_id, const GValue * value, GParamSpec * pspec);


GazetteWindow* gazette_window_construct (GType object_type) {
	GazetteWindow * self = NULL;
	GtkClutterEmbed* _tmp0_;
	ClutterStage* _tmp1_;
	ClutterStage* _tmp2_;
	ClutterStage* _tmp3_;
	ClutterStage* _tmp4_;
	ClutterColor _tmp5_ = {0};
	GtkClutterEmbed* _tmp6_;
	self = (GazetteWindow*) granite_widgets_composited_window_construct (object_type);
	gtk_window_set_type_hint ((GtkWindow*) self, GDK_WINDOW_TYPE_HINT_DESKTOP);
	gtk_window_set_resizable ((GtkWindow*) self, TRUE);
	_tmp0_ = (GtkClutterEmbed*) gtk_clutter_embed_new ();
	g_object_ref_sink (_tmp0_);
	_g_object_unref0 (self->priv->embed);
	self->priv->embed = _tmp0_;
	_tmp1_ = gazette_window_get_stage (self);
	_tmp2_ = _tmp1_;
	clutter_stage_set_use_alpha (_tmp2_, TRUE);
	_tmp3_ = gazette_window_get_stage (self);
	_tmp4_ = _tmp3_;
	_tmp5_.red = (guint8) 0;
	_tmp5_.green = (guint8) 0;
	_tmp5_.blue = (guint8) 0;
	_tmp5_.alpha = (guint8) 0;
	clutter_actor_set_background_color ((ClutterActor*) _tmp4_, &_tmp5_);
	_tmp6_ = self->priv->embed;
	gtk_container_add ((GtkContainer*) self, (GtkWidget*) _tmp6_);
	return self;
}


GazetteWindow* gazette_window_new (void) {
	return gazette_window_construct (TYPE_GAZETTE_WINDOW);
}


gint* gazette_window_reposition (GazetteWindow* self, int* result_length1) {
	gint* result = NULL;
	GdkRectangle geom = {0};
	GdkScreen* _tmp0_ = NULL;
	GdkScreen* _tmp1_ = NULL;
	gint _tmp2_ = 0;
	GdkRectangle _tmp3_ = {0};
	GdkRectangle _tmp4_;
	gint _tmp5_;
	GdkRectangle _tmp6_;
	gint _tmp7_;
	GdkScreen* _tmp8_ = NULL;
	gint _tmp9_ = 0;
	GdkScreen* _tmp10_ = NULL;
	gint _tmp11_ = 0;
	GdkRectangle _tmp12_;
	gint _tmp13_;
	GdkRectangle _tmp14_;
	gint _tmp15_;
	gint* _tmp16_ = NULL;
	gint* _tmp17_;
	gint _tmp17__length1;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = gdk_screen_get_default ();
	_tmp1_ = gdk_screen_get_default ();
	_tmp2_ = gdk_screen_get_primary_monitor (_tmp1_);
	gdk_screen_get_monitor_geometry (_tmp0_, _tmp2_, &_tmp3_);
	geom = _tmp3_;
	_tmp4_ = geom;
	_tmp5_ = _tmp4_.x;
	_tmp6_ = geom;
	_tmp7_ = _tmp6_.y;
	gtk_window_move ((GtkWindow*) self, _tmp5_, _tmp7_);
	_tmp8_ = gdk_screen_get_default ();
	_tmp9_ = gdk_screen_width ();
	_tmp10_ = gdk_screen_get_default ();
	_tmp11_ = gdk_screen_height ();
	gtk_window_resize ((GtkWindow*) self, _tmp9_, _tmp11_);
	_tmp12_ = geom;
	_tmp13_ = _tmp12_.width;
	_tmp14_ = geom;
	_tmp15_ = _tmp14_.height;
	_tmp16_ = g_new0 (gint, 2);
	_tmp16_[0] = _tmp13_;
	_tmp16_[1] = _tmp15_;
	_tmp17_ = _tmp16_;
	_tmp17__length1 = 2;
	if (result_length1) {
		*result_length1 = _tmp17__length1;
	}
	result = _tmp17_;
	return result;
}


ClutterStage* gazette_window_get_stage (GazetteWindow* self) {
	ClutterStage* result;
	GtkClutterEmbed* _tmp0_;
	ClutterActor* _tmp1_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->embed;
	_tmp1_ = gtk_clutter_embed_get_stage (_tmp0_);
	result = G_TYPE_CHECK_INSTANCE_TYPE (_tmp1_, clutter_stage_get_type ()) ? ((ClutterStage*) _tmp1_) : NULL;
	return result;
}


static void gazette_window_set_stage (GazetteWindow* self, ClutterStage* value) {
	g_return_if_fail (self != NULL);
	g_object_notify ((GObject *) self, "stage");
}


static void gazette_window_class_init (GazetteWindowClass * klass) {
	gazette_window_parent_class = g_type_class_peek_parent (klass);
	g_type_class_add_private (klass, sizeof (GazetteWindowPrivate));
	G_OBJECT_CLASS (klass)->get_property = _vala_gazette_window_get_property;
	G_OBJECT_CLASS (klass)->set_property = _vala_gazette_window_set_property;
	G_OBJECT_CLASS (klass)->finalize = gazette_window_finalize;
	g_object_class_install_property (G_OBJECT_CLASS (klass), GAZETTE_WINDOW_STAGE, g_param_spec_object ("stage", "stage", "stage", clutter_stage_get_type (), G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE));
}


static void gazette_window_instance_init (GazetteWindow * self) {
	self->priv = GAZETTE_WINDOW_GET_PRIVATE (self);
}


static void gazette_window_finalize (GObject* obj) {
	GazetteWindow * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, TYPE_GAZETTE_WINDOW, GazetteWindow);
	_g_object_unref0 (self->priv->embed);
	G_OBJECT_CLASS (gazette_window_parent_class)->finalize (obj);
}


GType gazette_window_get_type (void) {
	static volatile gsize gazette_window_type_id__volatile = 0;
	if (g_once_init_enter (&gazette_window_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (GazetteWindowClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) gazette_window_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (GazetteWindow), 0, (GInstanceInitFunc) gazette_window_instance_init, NULL };
		GType gazette_window_type_id;
		gazette_window_type_id = g_type_register_static (GRANITE_WIDGETS_TYPE_COMPOSITED_WINDOW, "GazetteWindow", &g_define_type_info, 0);
		g_once_init_leave (&gazette_window_type_id__volatile, gazette_window_type_id);
	}
	return gazette_window_type_id__volatile;
}


static void _vala_gazette_window_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec) {
	GazetteWindow * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, TYPE_GAZETTE_WINDOW, GazetteWindow);
	switch (property_id) {
		case GAZETTE_WINDOW_STAGE:
		g_value_set_object (value, gazette_window_get_stage (self));
		break;
		default:
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}


static void _vala_gazette_window_set_property (GObject * object, guint property_id, const GValue * value, GParamSpec * pspec) {
	GazetteWindow * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, TYPE_GAZETTE_WINDOW, GazetteWindow);
	switch (property_id) {
		case GAZETTE_WINDOW_STAGE:
		gazette_window_set_stage (self, g_value_get_object (value));
		break;
		default:
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}



